### ISSUE TITLE
Issue with task 9 of the "superposition" kata

### ISSUE THREAD

**Issue by Grebnedlog** [Microsoft/QuantumKatas#1]
The output of the reference function TwoBitstringSuperposition_Reference doesn't seem to be correct: For the bit string input b1=(false,true); b2=(true, false), calling DumpRegister on the qubit state returns:
`Ids:	[1;0;]
Wavefunction:
0:	1	0
1:	0	0
2:	0	0
3:	0	0
`
The way I understand the problem, I would expect an output such as:
`Ids:	[2;1;]
Wavefunction:
0:	0	0
1:	0.707107	0
2:	0.707107	0
3:	0	0
`
I'd welcome feedback on this issue.

**Comment by tcNickolas** [comment]
Could you please share the code you're using to get this result? 

I ran the following code:

    using (qs = Qubit[2]) {
        TwoBitstringSuperposition_Reference(qs, [false; true], [true; false]);
        DumpRegister("", qs);
    }

And it dutifully printed the expected state:

    Ids:    [1;0;]
    Wavefunction:
    0:      0       0
    1:      0.707107        0
    2:      0.707107        0
    3:      0       0

(After that it proceeded to throw `ReleasedQubitsAreNotInZeroState` exception, which confirms that the qubits are indeed not in zero state)

**Comment by Grebnedlog** [comment]
Strangely enough, when I was running the same code again today, it gave the expected output. Thanks for the feedback!
