### ISSUE TITLE
Convert the Katas to Jupyter Notebook format

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/QuantumKatas#105]
[The first batch](https://mybinder.org/v2/gh/Microsoft/QuantumKatas/master?filepath=index.ipynb) of the katas is converted to Notebook format. We'll need to convert the rest of the katas, so that all of them are available both as Notebooks and as regular projects. 

This is going to take some work, so I'd appreciate some help!

- [x] Basic Gates
- [x] Superposition
- [x] Measurements
- [x] Joint Measurements
- [x] Teleportation
- [x] Superdense Coding
- [x] Deutsch-Jozsa Alrorithm
- [x] CHSH Game
- [x] GHZ Game
- [x] Mermin-Peres magic square game
- [x] Grover's Algorithm
- [x] Solving SAT problems using Grover's algorithm
- [x] Solving graph coloring problems using Grover's algorithm
- [x] BB84 protocol
- [x] Phase Estimation
- [x] Bit-flip error correction code
- [x] Ripple-carry adder
- [x] Unitary patterns

**Comment by sdf94** [comment]
How can I help?

**Comment by tcNickolas** [comment]
Thank you for the offer! Do you want to try and convert Phase Estimation kata? It is slightly trickier than the ones already converted, since it uses a custom simulator to count the number of qubits allocated in some tasks. You'll need to remove `CounterSimulator.cs` from this project and to replace it with a reference to the simulator in `utilities/Common` - you can see how this is handled in https://github.com/microsoft/QuantumKatas/pull/155.

Let me know if you have any questions about the details!

**Comment by sdf94** [comment]
I am currently having problems with having the q# kernel in jupyter notebook (I already noted it on github), so I am going to have to spend some time with that. Meanwhile, if you have time to finish this last one in the next week, I would recommend it.

**Comment by tcNickolas** [comment]
No worries about the last kata, @jackhyder graciously picked it up.

@sdf94, did you figure out your trouble with the Q# kernel? (I couldn't find your question on our other repos)

**Comment by tcNickolas** [comment]
Thanks to the selfless work of @jimcristofono and @jackhyder, all the katas on the list have been converted to Jupyter Notebook format! Simon's algorithm kata is the only one not included in the list, but it requires a different kind of work, tracked separately in #138.

**Comment by tcNickolas** [comment]
The new kata [KeyDistribution_BB84](https://github.com/microsoft/QuantumKatas/tree/master/KeyDistribution_BB84) does not have a Jupyter Notebook version and needs one. Reopening this issue rather than creating a new one.

**Comment by sdf94** [comment]
> No worries about the last kata, @jackhyder graciously picked it up.
> 
> @sdf94, did you figure out your trouble with the Q# kernel? (I couldn't find your question on our other repos)

Yes I did. I had to do a clean download.

**Comment by sdf94** [comment]
> The new kata [KeyDistribution_BB84](https://github.com/microsoft/QuantumKatas/tree/master/KeyDistribution_BB84) does not have a Jupyter Notebook version and needs one. Reopening this issue rather than creating a new one.

Now that I got the hang of it a little bit, I think I can do this one.

**Comment by tcNickolas** [comment]
Thank you for the offer!! There is a PR actually open to migrate that kata, https://github.com/microsoft/QuantumKatas/pull/178 - I'm reviewing it now, so that should be covered.

If you're looking for something interesting to do, check out the other issues - I'll be opening some new ones for Hacktoberfest that should hopefully be easy to start with.
