### ISSUE TITLE
Should we use 'α' as variable name?

### ISSUE THREAD

**Issue by ganesshkumar** [microsoft/QuantumKatas#124]
I am using Jupyter Notebook. In the BasicGates python notebook I saw few parameters as 'α'. One has to copy and paste this variable everywhere they wish to use.

Should we continue using variables like 'α' or should we rename them to 'alpha'?

**Comment by tcNickolas** [comment]
I thought having Unicode α was cute, but, in retrospect, very few people will be able to type it in (I confess I just copy-pasted the character in this comment 😄), and having a character that you *have* to copy-paste every time you need it is frustrating. 

I agree this needs to be renamed, at least in the tasks (in reference solutions it's probably ok to keep it as α, though it can be done either way). Do you want to open a pull request to do the rename? If not, I'll get to it later.

**Comment by ganesshkumar** [comment]
Thanks for the quick reply. I shall raise a PR for this 😄
