### ISSUE TITLE
Wrong test name in Teleportation.ipynb

### ISSUE THREAD

**Issue by inchiosa** [microsoft/QuantumKatas#128]
To get Teleportation.ipynb to work, change ‘%kata T14_StandardTeleport_Test’ to ‘%kata T14_Teleport_Test’

**Comment by tcNickolas** [comment]
Good catch! I missed that one when I tested this Notebook.

A better fix would probably be renaming the test to `T14_StandardTeleport_Test` in `Tests.qs` - it will fit the usual test naming scheme of "test number - task name - Test suffix" better. Do you want to do this fix? If not, I'll get to it at some point.

**Comment by tcNickolas** [comment]
This has been fixed in #133.
