### ISSUE TITLE
Hi, there is any solutions to the Katas?

### ISSUE THREAD

**Issue by sdimantsd** [microsoft/QuantumKatas#149]
Thanks!

**Comment by tcNickolas** [comment]
Each kata has all reference solutions for the tasks (in `ReferenceImplementation.qs` file in the project).

We are starting to write "workbooks" for some of the katas, which will provide not only the code answer but also the details on how to arrive to this code (both the math behind the solution and the insights into non-trivial features of Q#, if any are used in the code). These are some time away from being released, though - stay tuned!

**Comment by sdimantsd** [comment]
thx
