### ISSUE TITLE
Update Q# language quick reference to latest syntax

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/QuantumKatas#188]
*This is a great first issue for somebody familiar with LaTeX but not very familiar with Q#!*

The [quick reference](https://github.com/microsoft/QuantumKatas/tree/master/quickref) has last been updated for Q# 0.3, which is almost a year old now. We need to update it to the latest version (currently 0.9) following the [Q# language documentation](https://docs.microsoft.com/en-us/quantum/language/). Some of the things that need to be added/updated, at a glance:

* Add syntax for array element assignment
* Add while loop
* Add syntax for allocating a single qubit and several qubits/qubit registers at once
* Separate a section on user-defined types and add more entries on it
* Add apply-and-reassign statements
* Add conjugation statements (`within ... apply ...`)
* Shorthand syntax `is Adj+Ctl`

There are probably other things I'm missing - this is just a list to start with.

Also, the list of resources needs to be reconsidered - for example, we have a lot more Q# repositories now compared to a year ago.

**Comment by sdf94** [comment]
Ill take this.

**Comment by tcNickolas** [comment]
Thank you for picking this up! Please don't hesitate to ask if you have any doubts about anything.

**Comment by tcNickolas** [comment]
To link the issue with the work in progress, the PR is open at https://github.com/microsoft/QuantumKatas/pull/207.

**Comment by tcNickolas** [comment]
This has been fixed in #207 - thank you!

The second part of the change would be to include more information on quantum primitives, such as quantum gates and measurements, and on the commonly used library methods such as `ApplyToEach`, but this can (and should!) be covered by a separate issue/PR.
