### ISSUE TITLE
Possible incorrect test data in kata SuperpositionOneMeasurement

### ISSUE THREAD

**Issue by wsgac** [microsoft/QuantumKatas#189]
I've been playing around, trying to simplify my solution to kata `SuperpositionOneMeasurement` in the `Measurements` section. The essential part of the reference implementation is the function `FindFirstSuperpositionDiff_Reference`, which detects at which position in the bit arrays occurs a "total difference", i.e. one has only `true` values and the other `false` or vice versa. Building on the assumption that `bits1` and `bits2` are isomorphic (`M ⨯ N`, as per the description) I came up with a simplified version of the function:
```
function findDiscrepancy(bits1: Bool[][], bits2: Bool[][], qs: Qubit[]) : Int {
        for (q in 0..Length(qs)-1) {
            mutable n1 = 0;
            mutable n2 = 0;
            for (s in 0..Length(bits1)-1) {
                if (bits1[s][q]) {
                    set n1 += 1;
                }
                if (bits2[s][q]) {
                    set n2 += 1;
                }
            }
            if (MyAbs(n1-n2) == Length(bits1)) {
                return q;
            }
         }
         return -1;
}
```
When using this function tests started to fail. I investigated this by inserting `Message` statements and inspecting the lengths of `bits1` and `bits2` and noticed that there are many cases in which they are different. The original function `FindFirstSuperpositionDiff_Reference` deals with it by comparing to two different lengths, but with the isomorphism assumption in force, the lengths should be the same, i.e. both functions should be equivalent. Am I missing something?

**Comment by tcNickolas** [comment]
You're right, nice catch - thank you!!

Originally PR #167 which introduced these tasks had test data only for both arrays having the same dimensions, but as I was reviewing it, I realized that the solution doesn't really depend on the exact number of terms in the superposition states we're trying to distinguish, so I suggested removing this constraint. Looks like we changed it everywhere except the task statement...

We need to re-phrase the task description for this task (and probably the next one as well - it says "The arrays describe the superposition states in the same way as in the previous task." which implies that the arrays have the same dimensions) to say that the arrays will have the same second dimension N, but might have different first dimensions M₁ and M₂.

Do you want to try and create a PR to fix the task description? (I'm not sure if you're participating in [Hacktoberfest](https://hacktoberfest.digitalocean.com/), if yes, this would be a good start at it!) If not, I'll get to fixing it at some point this week.

**Comment by wsgac** [comment]
Thanks for your clarification. I'll create a PR in the coming day or two.

I'm not participating in Hacktoberfest (yet). I might give it a try. Thanks for the suggestion :).

**Comment by wsgac** [comment]
Created a [PR](https://github.com/microsoft/QuantumKatas/pull/191) with the change.

**Comment by wsgac** [comment]
OK, I may have taken your suggestion about Hacktoberfest a bit too seriously :). I have three additional PRs offering conceptual simplifications of reference implementations.

**Comment by tcNickolas** [comment]
There is no such thing as taking Hacktoberfest too seriously, unless you're well in your third dozen of PRs during the first day 😄 Thank you - I'll take a closer look at them later today.
