### ISSUE TITLE
Update the katas to use most recent Q# features

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/QuantumKatas#190]
Q# evolution introduced some new language features in the past half a year:

* [within... apply... statement](https://docs.microsoft.com/quantum/user-guide/using-qsharp/operations-functions#conjugations)
* [ranges in array slicing](https://docs.microsoft.com/quantum/language/expressions#array-slices)
* features introduced in Q# 0.6 listed in [this blog post](https://devblogs.microsoft.com/qsharp/qsharp-06-language-features-and-more/)

It makes sense to go through the code and check for places where using the new features would improve code readability. Here is the list of all the katas, with ones that have already gone through the update marked as completed.

- [x] Deutsch–Jozsa algorithm (Notebook Tutorial)
- [x] Exploring Grover's search algorithm (Notebook Tutorial)
- [x] Basic quantum computing gates
- [x] Superposition
- [x] Measurements
- [x] Joint measurements
- [x] Teleportation
- [x] Superdense coding
- [x] Deutsch–Jozsa algorithm
- [x] Simon's algorithm
- [x] Grover's algorithm
- [x] Solving SAT problems using Grover's algorithm
- [x] Solving graph coloring problems using Grover's algorithm
- [x] CHSH game
- [x] GHZ game
- [x] Mermin-Peres magic square game
- [x] BB84 protocol
- [x] Phase estimation
- [x] Bit-flip error correcting code
- [x] Truth tables
- [x] Ripple-carry adder
- [x] Unitary Patterns
- [x] QFT
- [x] Distinguishing Unitaries

**Comment by avinashbhat** [comment]
Can I take this up?

**Comment by tcNickolas** [comment]
Yes, absolutely!

It probably makes sense to make a list of katas and go through them one by one, opening separate PRs for each kata that needs updates - this way each step has a smaller scope (and the overall work doesn't feel overwhelming) and the conflicts are less likely to occur.

**Comment by tcNickolas** [comment]
@avinashbhat Could you let us know much progress you've made on this issue? We're hosting a Hackathon tomorrow, and this issue is one of the easier ones to get started with, so if possible, I'd like to split the work on it among several people. On the other hand, I really don't want several people working on the same kata, so splitting it per kata seems like a good idea.

**Comment by avinashbhat** [comment]
It sounds like a good idea! These are the list of katas that are to be updated. I've marked the one I'm working on. It would be great if you reference the PRs back to this comment to track things.
- [x] Deutsch–Jozsa algorithm (Notebook Tutorial)
- [ ] Exploring Grover's search algorithm (Notebook Tutorial)
- [ ] Basic quantum computing gates
- [ ] Superposition
- [ ] Measurements
- [ ] Teleportation
- [ ] Superdense coding
- [ ] Deutsch–Jozsa algorithm
- [ ] Simon's algorithm
- [ ] Grover's algorithm
- [ ] Solving SAT problems using Grover's algorithm
- [ ] Solving graph coloring problems using Grover's algorithm
- [ ] CHSH game
- [ ] GHZ game
- [ ] Mermin-Peres magic square game
- [ ] BB84 protocol
- [ ] Phase estimation
- [ ] Bit-flip error correcting code
- [ ] Ripple-carry adder
- [ ] Unitary Patterns

[Changes](https://docs.microsoft.com/en-us/quantum/relnotes/?view=qsharp-preview#q-language-syntax-1) to be made.

**Comment by tcNickolas** [comment]
@avinashbhat Haven't heard from you in a while - are you still working on updating Q# in DJ algorithm tutorial?

**Comment by delbert** [comment]
i would like to work on the Superposition kata, if that is all right?

**Comment by tcNickolas** [comment]
@delbert Absolutely!

**Comment by delbert** [comment]
hello Everyone, i would like to work on the Measurements Kata now.

delbert

**Comment by tcNickolas** [comment]
Sounds great!

**Comment by delbert** [comment]
hello Folks, i'll take up Teleportation, next, if that makes the most sense.

**Comment by tcNickolas** [comment]
@delbert Sure!

**Comment by cdberkstresser** [comment]
Do you all have a Q# linter addon for VSCode / Visual Studio that can be utilized to help with this?

**Comment by tcNickolas** [comment]
No, there's no Q# linter at the moment. 

I'm not sure this kind of change is straightforward to automate if we're looking to maximize code readability. For example, referring to the 1st element of the array as Head() is a good idea in a context when it is treated differently from the rest of the array (and the rest of the array is treated uniformly, like in GHZ state preparation) but not so good idea if there are just 2 qubits. Analyzing patterns to figure out whether `within ... apply` or `ControlledOnBitString` is more readable also doesn't seem trivial to implement. 

I expect that when a linter is written, it will start with simpler things like code formatting. And we're already a third of the way there - we'll probably finish this issue before the linter :-)

**Comment by tcNickolas** [comment]
We can finally mark this issue as complete! Fantastic job everyone, thank you for your work on this!
