### ISSUE TITLE
Does this plan to grow for a long time

### ISSUE THREAD

**Issue by cuo9958** [Microsoft/QuantumKatas#2]
i hope it nice

**Comment by tcNickolas** [comment]
Yes, we definitely plan to expand the list of the topics, so that this project will be a proper introduction to quantum computing. I think at some point we'll run out of topics, but I don't see this happening in the next several months :-)

**Comment by uyaddayu** [comment]
look so cool but i am so poor about it

**Comment by tornodo** [comment]
maybe not

**Comment by cherrybuchanan4208** [comment]
How do I talk to or text or find dr halim I seen the new doc an he is taking me off my clonipin an Subutex an I have no doctor an will not see a doctor unless I get tarq halim back ppl out there help me please I am out of meds an he is the only doc that understand me and my head thank you God bless Cherry
