### ISSUE TITLE
DeutschJozsaAlgorithm tutorial: improve messaging for code samples

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/QuantumKatas#201]
In [this tutorial](https://github.com/microsoft/QuantumKatas/tree/master/tutorials/DeutschJozsaAlgorithm) the code cells alternate: some of them are kata-style tasks (are covered with tests and output "Success!" if solved correctly) and some of them (examples of oracles) are demo-style (define some Q# operations without running them, so output the names of the defined operations).

This difference can be confusing for some learners, especially if they tried some katas before that tutorial and got used to the "Success!" output. It would be nice to do one of the two things:

1. either have some wording before the samples saying something like "these are just code samples, you don't have to modify the code and they are not covered by tests"
2. or add some tests to cover them, so that they output "Success!" as well (this will also require splitting the cell with classical oracles into several). We could have tests for classical functions that actually print the outputs for all inputs, so that it's more visual.

**Comment by jackhyder-ms** [comment]
I can take this one if no one has yet.

**Comment by tcNickolas** [comment]
Fixed in #285.
