### ISSUE TITLE
Write PowerShell script to update QDK to the new version

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/QuantumKatas#204]
Updating QDK to the next version requires doing a fixed set of changes to an ever-growing set of files (see recent #179 and the most recent #235 for a list of files and changes). 

Currently we're using a generic Bash script to automate most of the change (see attached [updateQDKVersion.txt](https://github.com/microsoft/QuantumKatas/files/3769677/updateQDKVersion.txt)), but it would be nice to have a PowerShell script tailored to the Katas project.

**Comment by sdf94** [comment]
I will take this!

**Comment by tcNickolas** [comment]
Great, thank you!

**Comment by sdf94** [comment]
Could you give me a zipped up version of packages.config and the other folder for testing?

**Comment by tcNickolas** [comment]
Sorry, I'm not sure what exactly you need? To test the script, you can just run it on the master branch of the Katas with some arbitrary version like 1.2.3.4 and check that the version number has been updated in all the files covered in #235 (except .code-workspace file which was deleted independently), you shouldn't need anything extra.
