### ISSUE TITLE
Running jupyter notebook tutorials locally requires installing pytest

### ISSUE THREAD

**Issue by ivylee** [microsoft/QuantumKatas#223]
Hi thanks for putting together the tutorials!

I got started following https://github.com/microsoft/QuantumKatas#running-the-katas-locally-, the jupyter notebook tutorials use `pytest` for evaluation but it was not mentioned in the set up process. It was in the Dockerfile though.

**Comment by tcNickolas** [comment]
True, our instructions for running the katas are rather outdated, I will be taking a closer look at them next week. (You might have a similar problem with `matplotlib` for "Exploring Grover" tutorial)

I wonder which flavor of the installation instructions did you follow when installing Q#? I think my Python came from Miniconda install which already included a lot of Python tools, but that was the previous version of Q# install instructions, the current one at https://docs.microsoft.com/en-us/quantum/install-guide/ doesn't suggest Anaconda.

**Comment by ivylee** [comment]
I'm on Mac OS, I installed Python3 via Homebrew, it is located at `/usr/local/bin/python3` and version 3.7.4. For Q# I followed the first two sections of https://docs.microsoft.com/en-us/quantum/install-guide/index?view=qsharp-preview#develop-with-python. I have been using jupyter notebook for the tutorials. Hope it helps.

**Comment by ivylee** [comment]
You're right, I just got to VisualizingGroversAlgorithm and I had to install `matplotlib` manually, thanks for the heads up.

**Comment by sandramedina** [comment]
Ran into the same issue before realizing I needed to install pytest and also have a similar setup: Mac OS, Python3 via Homebrew

**Comment by tcNickolas** [comment]
Thank you for confirming! To my great embarrassment, I still have to carve out the time to update our installation instructions...
