### ISSUE TITLE
Typo in URL of Quirk

### ISSUE THREAD

**Issue by ivylee** [microsoft/QuantumKatas#226]
In tutorials/SingleQubitGates, the link to Quirk is incorrect https://github.com/microsoft/QuantumKatas/blob/master/tutorials/SingleQubitGates/SingleQubitGates.ipynb?short_path=511e2f8#L262, should be https://algassert.com/quirk.

**Comment by tcNickolas** [comment]
Great catch, thank you! 

Do you want to send a pull request to fix the link? If not, I'll get to it some time soon.

(Sorry for the delay replying to your other issues, I've been traveling and just now returning to the open-source work - I'll get to them as soon as possible!)

**Comment by ivylee** [comment]
@tcNickolas Sorry the first PR was misconfigured, the second one should be correct.

**Comment by tcNickolas** [comment]
Thank you! I merged the PR in the staging branch, will merge into master later today.
