### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by zzz6519003** [microsoft/QuantumKatas#229]
https://mybinder.org/v2/gh/Microsoft/QuantumKatas/master?filepath=BasicGates%2FBasicGates.ipynb

**Comment by tcNickolas** [comment]
Looks like the cached image of the repository somehow got invalidated, and building the new image keeps timing out... We'll keep looking into why this is happening; as a temporary workaround, try using the following link https://mybinder.org/v2/gh/Microsoft/QuantumKatas/drop-prebuild?filepath=index.ipynb - it might take 10-15 minutes to build but so far it hasn't timed out for me.

**Comment by zzz6519003** [comment]
Thanks！

Love the idea if one build, everyone share XD

**Comment by tcNickolas** [comment]
We've updated the Katas to the release 0.10.1911.1607 (thanks @bettinaheim!) which should fix this issue. Building the Binder image the first time after master is updated now takes ~25 minutes and it is a lot less likely to timeout on any individual kata.
