### ISSUE TITLE
(Harmless) Failures when Building the Katas docker image

### ISSUE THREAD

**Issue by vxfield** [microsoft/QuantumKatas#243]
I'm not sure if this is by-design, but while building the Katas docker image, it produces a couple warnings and several failures in the NbConvertApp markdown conversion.

Although they seem harmless and don't impede the generation of the docker image, it gives the impression that something went wrong in the process.

**Steps to repro:**
1) Run "docker build -t katas ." at the root of the repo, as suggested in the README.

**Warning example:**
```
Step 6/33 : RUN pip install "pytest"
 ---> Running in dc47a6915564
WARNING: The directory '/home/jovyan/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.

```

**Potential solutions to these warnings:**
A) Use the -H flag in sudo.
B) Install pytest in the user's folder without sudo (pip install --user pytest).

**Failure example:**
```
Step 23/33 : RUN ${HOME}/scripts/prebuild-kata.sh SuperdenseCoding
 ---> Running in 6e5cf347f452
Prebuilding: SuperdenseCoding.ipynb in SuperdenseCoding kata...
Microsoft (R) Build Engine version 16.3.0+0f4c62fea for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 57.32 ms for /home/jovyan/SuperdenseCoding/SuperdenseCoding.csproj.
  Restore completed in 442.28 ms for /home/jovyan/SuperdenseCoding/SuperdenseCoding.csproj.
  SuperdenseCoding -> /home/jovyan/SuperdenseCoding/bin/Debug/netcoreapp3.0/SuperdenseCoding.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:18.75
[NbConvertApp] Converting notebook SuperdenseCoding/SuperdenseCoding.ipynb to markdown
[NbConvertApp] Executing notebook with kernel: iqsharp
fail: Microsoft.Quantum.IQSharp.Snippets[0]
      QS6307: Not all code paths return a value.
fail: Microsoft.Quantum.IQSharp.Snippets[0]
      QS6307: Not all code paths return a value.
[NbConvertApp] Writing 6117 bytes to SuperdenseCoding/SuperdenseCoding.md
Removing intermediate container 6e5cf347f452
 ---> 803b8c2641bc
```

**Potential solutions to the failures:**
A) Leave it be, assuming this is by-design and the user is responsible to take care of the errors as part of the Kata exercise.
B) Make all code snippets compilable by commenting placeholders and returning dummy results.

**Comment by tcNickolas** [comment]
For the `pip install` warning, I agree that it would be nice to get rid of this warning.

* Adding `--user` option doesn't seem to help - I created a [branch](https://github.com/microsoft/QuantumKatas/compare/master...mariia/pip-install) with the change, and building it [on Binder](https://mybinder.org/v2/gh/Microsoft/QuantumKatas/mariia/pip-install?filepath=index.ipynb) still produces this error. 
* I suspect we won't have access to executing commands with `sudo` on Binder - when I try [another branch](https://github.com/microsoft/QuantumKatas/compare/master...mariia/sudo-pip), [Binder build](https://mybinder.org/v2/gh/Microsoft/QuantumKatas/mariia/sudo-pip?filepath=index.ipynb) doesn't recognize `sudo` as a command at all. I might have gotten the syntax wrong, though - do you have any suggestions?

The NbConvert failures are benign - a lot of the katas and especially the tutorials have intentionally invalid Q# code, designed for the user to fix / fill the gaps, so executing them as is will produce an error, but an expected one. I actually like this feature of the Notebooks, compared to the katas-as-Q#--projects which must have valid Q# code in all tasks to allow the project to compile - it allows us to not come up with confusing placeholder values (tasks that return an operation are particularly bad at this). 

Thank you for your vigilance!

**Comment by sdf94** [comment]
I saw that you used 
`RUN pip install "matplotlib"
RUN pip install "pytest"`
to:
`RUN sudo -H pip install "matplotlib"
RUN sudo -H pip install "pytest"`

But it is suppose to be like this:
`
RUN sudo pip install "matplotlib"
RUN sudo pip install "pytest"`

Have you tried that?

**Comment by sdf94** [comment]
Or adding user root to sudo:
`sudo adduser <username> sudo`

**Comment by tcNickolas** [comment]
We're planning to switch to building the Docker image ourselves and publishing it for consumption, so we will polish our Docker build, but not in the context of eliminating that specific warning. I'll close this issue, since it will be part of a larger effort.
