### ISSUE TITLE
Recursive Solution to Superposition -> FourBitstringSuperposition

### ISSUE THREAD

**Issue by cdberkstresser** [microsoft/QuantumKatas#249]
**Alternative Solution to add to reference implementations**

Would there be any interest in adding a recursive solution to the Superposition.ReferenceImplemention.qs file for the **FourBitstringSuperposition** task?  Personally, I struggled with the ancillae-based solution, but recursion made sense to me.  I wrote the following solution, which passes the unit test cases as well as offers extensibility to n-bit string superpositions.

Proposed additional solution:
```c#
// Task 15*. Superposition of four bit strings
    // Inputs:
    //      1) N qubits in |0...0⟩ state
    //      2) four bit string represented as Bool[][] bits
    //         bits is an array of size 4 x N which describes the bit strings as follows:
    //         bits[i] describes the i-th bit string and has N elements.
    //         All four bit strings will be distinct.
    //
    // Goal: create an equal superposition of the four basis states given by the bit strings.
    //
    // Example: for N = 3 and bits = [[false, true, false], [true, false, false], [false, false, true], [true, true, false]]
    //          the state you need to prepare is (|010⟩ + |100⟩ + |001⟩ + |110⟩) / 2.
   operation FourBitstringSuperposition (qs : Qubit[], bits : Bool[][]) : Unit {
        FourBitstringSuperposition_Recursive(new Bool[0],qs,bits);
    }

    operation FourBitstringSuperposition_Recursive (currentBitString : Bool[], qs : Qubit[], bits : Bool[][]) : Unit {
        //an array of bit strings whose columns we are considering begin with |0>
        mutable zeroLeads = new Bool[][0];
        //an array of bit strings whose columns we are considering begin with |1>
        mutable oneLeads = new Bool[][0];
        //rows is more intuitive to read
        let rows = Length(bits);
        //figure out what percentage of the bits should be |0>
        if (rows >= 1 and Length(currentBitString) < Length(qs)) {
            for (row in 0..rows-1) {
                if (bits[row][Length(currentBitString)]) {
                    set oneLeads = oneLeads + [bits[row]];
                } else {
                    set zeroLeads = zeroLeads + [bits[row]];
                }
            }       
            //rotate the qubit to make the percentage happen based on the previous bit string
            //for the first path through when bitstring is of zero length, it should do the rotation regardless.
            let theta = ArcCos(Sqrt(IntAsDouble(Length(zeroLeads))/IntAsDouble(Length(bits))));
            (ControlledOnBitString(currentBitString, Ry))(qs[0..Length(currentBitString)-1], (2.0 * theta , qs[Length(currentBitString)]));
            //call myself again based on the bit strings so far.
            FourBitstringSuperposition_Recursive(currentBitString + [false],qs,zeroLeads);
            FourBitstringSuperposition_Recursive(currentBitString + [true],qs,oneLeads);
        } 
        
    }
```

**Comment by cdberkstresser** [comment]
Also, as long as the ControlledOnBitString continues to handle the "no control" the same, you can do this with about half the code:
```c#
operation FourBitstringSuperposition (qs : Qubit[], bits : Bool[][]) : Unit {
        FourBitstringSuperposition_Recursive(new Bool[0],qs,bits);
    }

    operation FourBitstringSuperposition_Recursive (currentBitString : Bool[], qs : Qubit[], bits : Bool[][]) : Unit {
        //an array of bit strings whose columns we are considering begin with |0>
        mutable zeroLeads = new Bool[][0];
        //an array of bit strings whose columns we are considering begin with |1>
        mutable oneLeads = new Bool[][0];
        //rows is more intuitive to read
        let rows = Length(bits);
        //figure out what percentage of the bits should be |0>
        if (rows >= 1 and Length(currentBitString) < Length(qs)) {
            for (row in 0..rows-1) {
                if (bits[row][Length(currentBitString)]) {
                    set oneLeads = oneLeads + [bits[row]];
                } else {
                    set zeroLeads = zeroLeads + [bits[row]];
                }
            }       
            //rotate the qubit to make the percentage happen based on the previous bit string
            (ControlledOnBitString(currentBitString, Ry))(qs[0..Length(currentBitString)-1], (2.0 * ArcCos(Sqrt(IntAsDouble(Length(zeroLeads))/IntAsDouble(Length(bits)))) , qs[Length(currentBitString)]));
            //call myself again based on the bit strings so far.
            FourBitstringSuperposition_Recursive(currentBitString + [false],qs,zeroLeads);
            FourBitstringSuperposition_Recursive(currentBitString + [true],qs,oneLeads);
        } 
        
    }
```

**Comment by cdberkstresser** [comment]
The ControlledOnBitString method seems to do the rotation regardless on an empty control.  If that behavior is planned to be maintained, the code contracts nicely to the edit above because the first rotation has to happen.  Hopefully it is readable enough to get the strategy across...
Thanks!

**Comment by tcNickolas** [comment]
This definitely looks interesting! I think that with a bit more generalization you can get from this solution all the way to [the one we use in our library](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.preparation.preparearbitrarystate). 

I think it would be a better fit for the [Superposition workbook](https://github.com/microsoft/QuantumKatas/blob/master/Superposition/Workbook_Superposition.ipynb), so that you could include a step-by-step explanation of how to get to this solution along with the code itself. @jimcristofono and @ScottCarda-MS are working on the workbook for task 15 now - once they are done, you could add this solution to it. Would that work for you?

**Comment by cdberkstresser** [comment]
I'd be happy to do that if it helps.  

I didn't know about the PrepareArbitraryState() method, so thanks for pointing that out.  It would definitely be more elegant to just use it than recursion
```c#
    //assumes appropriate includes for Microsoft.Quantum.{Preparation,Arithmetic}
    operation FourBitstringSuperposition (qs : Qubit[], bits : Bool[][]) : Unit {
        mutable coefficients = new ComplexPolar[PowI(2,Length(qs))];
        for (row in 0..Length(bits)-1) {
            set coefficients w/= BoolArrayAsInt(bits[row]) <- ComplexPolar(1.0,0.0);
        }
        PrepareArbitraryState(coefficients,LittleEndian(qs));
    }
```
Would the recursive solution still be useful, or is it better to skip that and utilize the PrepareArbitraryState() approach to superposition problems?

**Comment by ScottCarda-MS** [comment]
It was my understanding that the PrepareArbitraryState method was not to be used in this Kata as it makes the tasks trivial. @tcNickolas Maybe I misunderstood?

**Comment by tcNickolas** [comment]
Yea, exactly! We use these tasks as training material to build up skills on state manipulation, and describing a recursive solution would be very useful for this purpose - more useful than just referring to a library function that does all the magic for us but doesn't teach the learner any interesting way of thinking.

**Comment by cdberkstresser** [comment]
Ok.  Great!  That makes sense.

**Comment by tcNickolas** [comment]
@cdberkstresser The workbook for task 15 of the Superposition kata is finally [merged to master](https://github.com/microsoft/QuantumKatas/blob/master/Superposition/Workbook_Superposition_Part2.ipynb) (sorry it took me so long to review it!) 

If you're still interested in contributing a description of the recursive solution, you're most welcome to do so!

**Comment by cdberkstresser** [comment]
@tcNickolas Would be happy to!  Hoping to sit down with this on the upcoming weekend.

**Comment by cdberkstresser** [comment]
Submitted Pull Request #324 .  Thanks!
