### ISSUE TITLE
The Latex code is not getting displayed properly for LinearAlgebra.ipynb

### ISSUE THREAD

**Issue by der-datenzauberer** [microsoft/QuantumKatas#269]
![image](https://user-images.githubusercontent.com/11174526/72551230-74086080-38ba-11ea-854d-2bec965f2a87.png)

**Comment by tcNickolas** [comment]
This is very weird... Big LaTeX formulas look like this indeed in the first few seconds after the notebook is opened, while the earlier formulas load, but they get formatted very quickly after that, I cannot reproduce this unformatted view showing for longer than that...

![image](https://user-images.githubusercontent.com/10113024/72552896-9c597600-384c-11ea-860c-ad8019146192.png)

1. Does this behavior persist?
2. Which is the earliest formula that does not render, and what are some other examples of problematic formuals? For example, it could be that your set up doesn't like `\color` tag which is first used in Matrix Multiplication section.
3. Could you please share the details of your set up?
4. Could you check whether Binder setup (https://mybinder.org/v2/gh/Microsoft/QuantumKatas/master?filepath=index.ipynb) renders all formulas for you? If this is some kind of browser issue and not Jupyter setup, it could be the case

**Comment by der-datenzauberer** [comment]
Hi @tcNickolas , looks like the issue got resolved. The Latex is rendering properly both on binder and local Jupyter Notebook.
