### ISSUE TITLE
Typo in QuantumKatas Complex Arithmetic Tutorial Solutions

### ISSUE THREAD

**Issue by sandramedina** [microsoft/QuantumKatas#270]
https://github.com/microsoft/QuantumKatas/blob/master/tutorials/ComplexArithmetic/Workbook_ComplexArithmetic.ipynb

In the solution to "Exercise 1: Powers of i" there is a table provided with "Power of i" on top and "Result" on bottom. I believe the answers for i^3 and i^7 should be -i instead of i? I thought my math might be wrong but double checked here and it seems correct 

https://www.wolframalpha.com/input/?i=i%5E7

**Comment by tcNickolas** [comment]
You're right, that's a very embarrassing typo - thank you for reporting it!

Do you want to open a pull request with a fix? If not, I'll get to fixing it some time over the weekend.

**Comment by sandramedina** [comment]
Just made one!

**Comment by tcNickolas** [comment]
Fixed in #271.
