### ISSUE TITLE
Confusing little endian

### ISSUE THREAD

**Issue by jks-liu** [microsoft/QuantumKatas#273]
These Katas just try to avoid the problem of endian, which just makes me more confused. Some place (I forget where, I even can not find endian information from the API reference like [ControlledOnInt](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.canon.controlledonint?view=qsharp-preview)) says it is little endian. Below are my understandings, are they correct? (I use row vectors for column vectors)

```
|00> = |0> = [1 0 0 0]
|01> = |2> = [0 0 1 0]
|10> = |1> = [0 1 0 0]
|11> = |3> = [0 0 0 1]
```

**Comment by tcNickolas** [comment]
Different katas use different notations. UnitaryPatterns says explicitly that it uses little endian; Superposition says that it uses big-endian (in the task 10 in which it relies on bitstring-to-integer conversion). 

Most of the katas use Dirac notation and thus use big-engian implicitly: |01⟩ is 1 and |10⟩ is 2. This corresponds to what you get if you convert Dirac notation to tensor product notation: 

![image](https://user-images.githubusercontent.com/10113024/72688215-d8ddd980-3ab9-11ea-867f-52e442e747b2.png)

Library operations use mostly little-endian - ControlledOnInt definitely does. I agree that API documentation should mention this more prominently!

**Comment by jks-liu** [comment]
@tcNickolas Thanks. It is very helpful.

**Comment by jks-liu** [comment]
@tcNickolas Thanks. It is very helpful.
