### ISSUE TITLE
Cryptography Kata

### ISSUE THREAD

**Issue by daniel-melia** [Microsoft/QuantumKatas#28]
Hi. 

I'd like to create a kata on quantum cryptography, is it alright to get that put on the roadmap? Intend to introduce the coder to a quantum key distribution scheme, show how it could be used to create a one-time pad, and have them test whether the line is being eavesdropped on when generating the key.

Thanks,
Daniel

**Comment by daniel-melia** [comment]
Great, quantum key distribution sounds good to me. BB84 is the natural place to start; will see if it feels right to introduce other protocols as part of the same kata as I develop it.

**Comment by tcNickolas** [comment]
Hey @daniel-melia, just wanted to check whether you're still working on this kata? Please let me know if you need any help from me.

**Comment by daniel-melia** [comment]
Hi @tcNickolas, had to limit my keyboard time and put personal projects on hold for a few months after developing RSI! Have it under control now so will be cracking on with the kata.

**Comment by tcNickolas** [comment]
No rush, and glad you're feeling better!
