### ISSUE TITLE
Add support for rich state display in Jupyter Notebooks.

### ISSUE THREAD

**Issue by cgranade** [microsoft/QuantumKatas#292]
As of #290, the katas now use a version of IQ# that includes the enhancements from https://github.com/microsoft/iqsharp/pull/81. By calling the `WithJupyterDisplay` extension method at simulator creation time, the `%kata` magic can thus be extended with support for this new functionality.

**Comment by vivanwin** [comment]
I can have a look at this. To implement correctly there is an open [issue](https://github.com/microsoft/iqsharp/issues/130) in the IQSharp project which probably needs to be solved first.

**Comment by tcNickolas** [comment]
This should be addressed in the next release following https://github.com/microsoft/QuantumKatas/pull/344. I'll close this issue for now, and reopen if it turns out more work is needed. Thank you @cgranade for flagging this and @vivanwin for working on this!
