### ISSUE TITLE
Task description for BasicGates / BellStateChange3 doesn't mention `Controlled`

### ISSUE THREAD

**Issue by cgranade** [microsoft/QuantumKatas#293]
As discussed in #290, the `BellStateChange3` task in the **BasicGates** kata currently rejects `Y` as a solution as `Y` differs from the intended solution by an unobservable global phase. That is, the task requires that the operation act correctly when called with the `Controlled` functor as well as when called in an uncontrolled manner. The task description doesn't reflect this requirement explicitly, such that the participant has to know that's what the `is Adj + Ctl` signature in the task definition indicates.

**Comment by vivanwin** [comment]
I will have a look at this
