### ISSUE TITLE
Description of the action of the eavesdropper is not correct

### ISSUE THREAD

**Issue by crazy4pi314** [microsoft/QuantumKatas#296]
I found that task 3.1 in the [Key Distribution Kata](https://github.com/microsoft/QuantumKatas/tree/master/KeyDistribution_BB84) is incorrect in describing what an eavesdropper does in and to the quantum channel, and I wanted to make a few comments as a researcher in QKD.

The task description is as follows:
> In this task you will try to implement an eavesdropper, Eve. 
>
>Eve will intercept a qubit from the quantum channel that Alice and Bob are using. 
>She will measure it in either the $|0\rangle$ / $|1\rangle$ basis or the $|+\rangle$ / $|-\rangle$ basis,
>reconstruct the qubit into the original state and send it back to the channel. 
>Eve hopes that if she properly reconstructs the qubit after measurement she won't be caught!

The statement "reconstruct the qubit into the original state and send it back to the channel" violates no-cloning and is not what Eve does when doing and intercept-and-resend attack. She needs to prepare a new qubit in the basis she measured in and with the bit value she measured. It would also be helpful to talk about what factors Bob would notice that would indicate that Eve was caught (error rates) and how she could circumvent these.

**Comment by tcNickolas** [comment]
Well, reconstructing the qubit state is what Eve would like to do ideally. I don't think it violates the no-cloning theorem, since she wouldn't end up with a copy of the qubit state herself? 

I agree that the wording can be changed to be more careful, though. Thank you!

(Again, sorry for the delay replying!)

**Comment by crazy4pi314** [comment]
While reconstructing would be ideal for Eve to do, given she has no prior information about what is being sent she cannot reproduce the states with perfect fidelity by no cloning. I'll take a stab at rewording in #297 and see if that's ok.
