### ISSUE TITLE
Math expressions would not render correctly when Jupyter notebook used locally in VS Code.

### ISSUE THREAD

**Issue by jkovzels** [microsoft/QuantumKatas#313]
Most likely, it is a problem of VS Code implementation of Jupyter but math expression with `\\` line breaks will render with **$$** and ruin the at block unless closing `&&` moved to the new line.

here is an example from Complex Arithmetic:
![image](https://user-images.githubusercontent.com/351671/77834903-9f27ef80-7148-11ea-9d8c-87516d676da6.png)

**Comment by tcNickolas** [comment]
I'll admit I've never tried using the Jupyter Notebooks in VS Code, so it will take me a while to reproduce the issue. Thank you for reporting it!

If you have found a simple fix that renders the notebooks better in VS Code (without breaking them in regular Jupyter!), would you be willing to send a pull request with the fix?

**Comment by jkovzels** [comment]
I'll admit that after digging deeper into it I can recommend not to use  Jupyter Notebooks in VS Code :). 
Experience is not good, notebook does not look good, fonts, line length, local links not working, an overall jerkiness. I would recommend people to run the notebooks locally in the browser at this point.

That said, workaround is to regex replace all `([^"\\n])\$\$` with `\1\\n\$\$`: all `$$` with leading character except if character is " or new line, replace with leading char (group `\1`) and `$$`.
But I do not thing that anyone should do that. Fix should come from VS Code Python plugin team.

**Comment by tcNickolas** [comment]
Thank you for the investigation! This is very helpful - now I know not to spend too much time on this :-)
