### ISSUE TITLE
VS can't find the tests

### ISSUE THREAD

**Issue by TTeschitsch** [microsoft/QuantumKatas#316]
Hello,

My Visual Studio can't find the tests for the katas (I first tried with BasicGates).

I have an error in the ouput pane - Tests (message in attachment). The basic "Hello world" application works great and the build of Basic Gates is successful.

I have VS2019 Pro with .NET Core 3.1 and I cloned the git repository without any modification.

Thanks for your help!
[error.txt](https://github.com/microsoft/QuantumKatas/files/4427523/error.txt)

**Comment by bettinaheim** [comment]
Hi @TTeschitsch, 
Could you try adding 
`<PlatformTarget>x64</PlatformTarget>`
to the test project file? It shouldn't be needed, but it's a quick thing to try.

**Comment by TTeschitsch** [comment]
This is already set to x64 :(

**Comment by tcNickolas** [comment]
Could you please provide more details on your setup? 
* The version of .NET Core (can be obtained using `dotnet --version`)
* The version of VS (Help -> About Microsoft Visual Studio)
* The last commit in the katas? (last entry in `git log` - is it "Update QDK to version 0.11.2003.3107" or an earlier commit?)

**Comment by TTeschitsch** [comment]
- **The version of .NET Core (can be obtained using `dotnet --version`)**
   => Unfortunately, this command line return : "Unhandled exception. System.BadImageFormatException: Tentative de chargement d'un programme de format incorrect. (0x8007000B)". But, in the control panel, I see the installed version is "Microsoft .NET Core SDK 3.1.201 (x64)".

- **The version of VS (Help -> About Microsoft Visual Studio)**
   => Microsoft Visual Studio Professional 2019
Version 16.5.2

- **The last commit in the katas? (last entry in `git log` - is it "Update QDK to version 0.11.2003.3107" or an earlier commit?)**
   => "[Measurements] Create workbook for part II tasks (#305)" right after the one quoted.

**Comment by bettinaheim** [comment]
It looks like your dotnet version is not installed properly. The BadImageFormatException is usually related to a discrepancy between x64 and x86. Could you uninstall the 3.1.201 version using the control panel, then click on the "Download .NET Core Sdk" button [here](https://dotnet.microsoft.com/download), and install the downloaded dotnet? The `dotnet --version` command should hopefully succeed after that.

**Comment by TTeschitsch** [comment]
Now, the `dotnet --version` command returns "2.2.203" :( I think this is because I have sdks installed here : `C:\Program Files (x86)\dotnet\sdk`.

I renamed "dotnet" to "dotnet-old" (in the x86 folder) and, this time, the command line returns : "3.1.201" ! And the unit tests work :)

Thanks for the help !
