### ISSUE TITLE
MagicSquareGame problems in understanding

### ISSUE THREAD

**Issue by mbuchberger1967** [microsoft/QuantumKatas#323]
Hi @tcNickolas 
I spent already several days and nights and had a hard time but I cannot understand the MagicSquareGame kata 100%.
I managed to understand the kata, and also the articles up to a certain point, but then the articles end with "as it can be easily verified ...."  and I cannot follow this.
I wanted to ask you Mariia, may I ask you some questions about this kata?
And should I do this via this issue or would you orefer some other communication channel?

And please, if I bother you too much just tell me.
Thanks in advance
Markus

**Comment by tcNickolas** [comment]
You're most welcome to ask questions! However, if the question is more about the algorithm itself than about some Q# issue (which might be the case here?), I would recommend [Quantum Computing SE](https://quantumcomputing.stackexchange.com/), for several reasons:
* it's a lot easier to write math there using LaTeX than on GitHub (which doesn't really support formulas) - one can only get so far using Unicode!
* I watch SE as well as the Katas repo, but in addition you get access to a whole community of quantum computing experts who might be able to explain things a lot better (and faster) than I :-)

**Comment by tcNickolas** [comment]
@mbuchberger1967 So do you have a specific question about this kata? I'm not sure what's my next action for this issue is, since there is no clear question here...

**Comment by mbuchberger1967** [comment]
@tcNickolas Sorry, I was busy the last week. It is more about the algorithm itself, so I will close thi sissue here and will post my questions to Quantum Computing SE, as you proposed it.

Thanks a lot,
Markus

**Comment by tcNickolas** [comment]
Sounds good - I'll keep an eye on SE :-)

**Comment by mbuchberger1967** [comment]
Hi,
I created this question:
https://quantumcomputing.stackexchange.com/q/11810/11909

and this one:
https://quantumcomputing.stackexchange.com/q/11812/11909

Would be great if you can help me with those
Thx a lot.
Markus

Von: Mariia Mykhailova <notifications@github.com>
Gesendet: Donnerstag, 30. April 2020 21:19
An: microsoft/QuantumKatas <QuantumKatas@noreply.github.com>
Cc: Markus <markus@markusbuchberger.de>; State change <state_change@noreply.github.com>
Betreff: Re: [microsoft/QuantumKatas] MagicSquareGame problems in understanding (#323)


Sounds good - I'll keep an eye on SE :-)
