### ISSUE TITLE
Miscellaneous improvements to existing tutorials

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/QuantumKatas#328]
Here are some ideas for improvements to the [existing tutorials](https://github.com/microsoft/QuantumKatas/tree/master/tutorials):

- [x] Qubit:
   Update section "Demo: Examining Qubit States in Q#" with the new (visual) format of DumpMachine output
- [x] Multi-qubit gates: 
  * [x] Add a section on ket-bra notation for multi-qubit gates
  * [x] Describe the usage of multi-qubit gates on non-adjacent qubits (both in Dirac notation and in matrix notation, the latter with a worked-out 3-qubit example including swapping the qubits, applying the gate on adjacent qubits and undoing the swap)
- [x] Deutsch-Jozsa algorithm:
  What happens if the function is neither constant nor balanced? How exactly does the wavefunction look like for various functions? (Offer the learner some exercises/experimentation around this)
- [ ] Grover search algorithm:
  * [ ] What happens if there are no solutions?
  * [ ] What happens if solutions make up exactly half of the search space?
  * [ ] What happens if solutions make up more than half of the search space? How to handle this?

**Comment by vivanwin** [comment]
Hi can pickup the first point.

**Comment by sincak** [comment]
What kind of system is the %package Microsoft.Quantum.Katas::0.11.2003.3107 command in your Jupyter notebooks supposed to work on? It doesn't work on Linux or Windows (even after loading #Q SDK)

**Comment by tcNickolas** [comment]
@sincak It's supposed to work on both Linux and Windows (and macOS too, I think). Did you do all the steps of installing Jupyter Notebooks and IQ# as described in the [installation guide](https://docs.microsoft.com/en-us/quantum/install-guide/qjupyter), so that running `dotnet iqsharp --version` from command line gives you an IQ# version that matches the one in the `%package` command?

**Comment by ed1d1a8d** [comment]
A couple suggestions for the reference solutions to the PhaseEstimation kata:

- For task 1.4, perhaps a reference solution based on calling `QFT`/`QFTLE` could be given. Currently the reference solution just calls the `QuantumPhaseEstimation` function from the standard library.
- For task 2.2, the reference solution may be more complicated than necessary. You can first use the circuit in 2.1 with U^2 to determine whether the eigenvalue belongs in {1, -1} or {i, -i}, and then you can use the circuit in 2.1 with U and an appropriate rotation to fully determine the eigenvalue.

**Comment by tcNickolas** [comment]
@ed1d1a8d, these are very good points, thank you!
* For 1.4, yes, it's definitely possible to have an alternate reference solution. The existing one targets the use of libraries rather than lower-level implementation details, both are valid approaches but with different learning focus.
* For 2.2, agreed, the existing solution is quite suboptimal - I was not entirely comfortable with phase estimation a year ago when I wrote it :-)

Would you be interested in sending a pull request adding an alternate reference solution for 1.4 and replacing solution to 2.2? If not, I'll get to it at some point but not in the next three weeks...

**Comment by ed1d1a8d** [comment]
Sure, I'd be happy to send in a pull request. I know you guys are probably busy preparing the Codeforces Q# contest :)

**Comment by jainvasu631** [comment]
Hi I can pickup the 2 points on Multi-qubit gates

**Comment by jainvasu631** [comment]
I can take up first 2 points of Grover's Algorithm. I also wish to expand the Grover's Algorithm Kata to perhaps give a better explanation and analysis of the Algorithm.

**Comment by tcNickolas** [comment]
@jainvasu631 

Sounds good on the first two points of Grover's algorithm!

For expanding the kata, I was thinking that we need a low-level tutorial on Grover's search, a bit similar to what is done in https://github.com/microsoft/MLADS2020-QuantumClassification/, so that the low-level tutorial would cover the implementation of the algorithm itself, and the existing high-level picks it up from there. It's probably similar to what you're thinking, but I usually stick to the difference between a "kata" (a series of exercises without theory) and a "tutorial" (explanation of theory accompanied by demos and exercises).

**Comment by jainvasu631** [comment]
@tcNickolas I am slightly confused as to the best way to go about this. The existing Grover's Algorithm Kata essentially breaks down the Algorithm into its primitive steps and asks the reader to implement them. It does not offer any insight into why this works.  

Should this proposed tutorial be essentially a walkthrough of the Algorithm which explains what each steps does, the analysis behind it (simplified to certain extent). All these to me seem necessary in some form as without these it isn't easy to explain first 2 points you wrote above. Without the analysis, It might seem abrupt to inform the reader that - 
1. For Point 1 when no solutions are present, each Iteration does nothing to the qubits.
2. For Point 2 when number of solutions is exactly half each Iteration merely adds global phase of -1 to the qubits.
 
Assuming we do write all this with analysis in a workbook called *Tutorial_GroversAlgorithm*. Then these last 2 points also belong in this Tutorial.  

However **GroversAlgorithm** Kata isn't the only Kata based on a Singular Algorithm. One can argue that **PhaseEstimation** needs to be given a similar treatment.  If we continue in this manner, we could probably broadly divide all Kata's into two types.  
**Single Algorithm Katas** such as *Grover's Algorithm* or *Phase Estimation* etc and those which are **Application/Puzzle Based Katas** or puzzle like such as *DistinguishUnitaries* and *UnitaryPatterns*.   
The former Katas need to have a Tutorial (like ```Tutorial_GroversAlgorithm```) to explain the Algorithm in detail and the latter need to have Workbook (like ```Workbook_UnitaryPatterns```) to explain the solutions.

Let me know what you think.

**Comment by jainvasu631** [comment]
@tcNickolas  I have added the relevant sections in VisualizingGroversAlgorithm notebook in Pull Request #449
