### ISSUE TITLE
Problem in Qubit tutorial

### ISSUE THREAD

**Issue by theerfan** [microsoft/QuantumKatas#340]
In the "Demo: Examining Qubit States in Q#" part of the [Qubit tutorial](https://github.com/microsoft/QuantumKatas/blob/master/tutorials/Qubit/Qubit.ipynb), we have:
![image](https://user-images.githubusercontent.com/11455681/80893620-53d5a380-8ce9-11ea-9a6c-cd09795552e3.png)
Where DumpMachine's results are  inconsistent with the actual state. The |1> portion of the state should have an _i_ coefficient but it doesn't. (If I'm not wrong, the original state used to be |_-_>)

**Comment by tcNickolas** [comment]
Indeed, the *i* got lost when converting the example of text output to a screenshot of a visual output. We'll fix that. Thank you for catching this!
