### ISSUE TITLE
Grover's Algorithm 1.4 error

### ISSUE THREAD

**Issue by BrokenDuck** [microsoft/QuantumKatas#345]
I am quite puzzled at how the 1.4 task works. I understood the solution with the phase kickback trick. However, every time I execute it, it is outputting : 
`Qubit in invalid state. Expecting: Zero`
`	Expected:	0`
`        Actual:	0,5000000000000007`
`Try again!`
This is quite puzzling as when I am using the `DumpMachine()` function from Microsoft.Quantum.Diagnostics, the machine is in a weird state. At the beginning, the input register is in a random superposition state out of 3 qubits. Then, I use the new qubit as the target qubit and the number of possible state goes up (logically), but then I can do whatever I want with the new qubit and it will not change the state the machine is in. I also want to point out this happens when I execute the solution given in the reference file.

I hope you can help me with this since I am quite lost.

**Comment by tcNickolas** [comment]
Could you please provide the code you're trying? I have just double-checked the task and the following code passes the test, so the reference solution is correct. 

    function OracleConverter (markingOracle : ((Qubit[], Qubit) => Unit is Adj)) : (Qubit[] => Unit is Adj) {
        return OracleConverter_Reference(markingOracle);
    }

**Comment by BrokenDuck** [comment]
This is the definition of the operation which was put in a cell above the function and was run before :
```
operation OracleConverterImpl_Reference (markingOracle : ((Qubit[], Qubit) => Unit is Adj), register : Qubit[]) : Unit is Adj {
    using (target = Qubit()) {
        within {
            X(target);
            H(target);
        } apply {
            markingOracle(register, target);
        }
    }
}
```
And this is the function to call the operation :

**Comment by tcNickolas** [comment]
Sorry, I was a bit hasty in my earlier copy-paste, of course if you want to write the solution from scratch it should be as you listed. But I cannot reproduce the failure; when I try to do exactly what you did, the test passes:

![image](https://user-images.githubusercontent.com/10113024/81510987-e7e7d200-92ca-11ea-9900-f5a6129a52a3.png)

I'm puzzled as for what could be going wrong - any issues in the local QDK setup usually manifest before one can get the test results... Are you running this on Binder or on your local setup? Are you getting this behavior when you run the cells with this code from scratch? Is it possible that you executed the cells in a different order, or they had different code in them the first time you executed them?

**Comment by BrokenDuck** [comment]
Whilst I was rechecking if there was any difference I changed the name of the function from "OracleConverter_Reference" to "OracleConverter" and ran the cell again (with the operation already defined) and **it suddenly worked**. Black magic ! When I changed it back to "OracleConverter_Reference" it also worked ! I am quite puzzled. I am running this on local on version 0.11.2003.3107.
