### ISSUE TITLE
Problems in understanding the solution for Measurements - Task 2.3**. Peres/Wooters game

### ISSUE THREAD

**Issue by mbuchberger1967** [microsoft/QuantumKatas#349]
Hi @tcNickolas  and all others,
I have big problems in understanding the solution for 2.3 Peres/Wooters Game:

1. M' is not unitary (cols dont have norm = 1)
2. why do you choose 
![grafik](https://user-images.githubusercontent.com/25125667/81611570-90855700-93db-11ea-84e8-fe33e8dc2342.png)
and not orthogonal vectors to A, B, C?
Some how you do this then in the embedding step, I guess??
3. How exactly do you construct  M'? I cannot see how you use M to embed it into M' exactly... It is somehow contained in M', but the columns are shuffeled? Can you explain your approach?
3b. While discussing with someone on stack-exchange he gave me this proposal which seems to be more straight forward to me...

![grafik](https://user-images.githubusercontent.com/25125667/81611644-b14dac80-93db-11ea-963a-d1520c8f9411.png)

![grafik](https://user-images.githubusercontent.com/25125667/81611675-bd396e80-93db-11ea-81a3-3bdc7e32c9f9.png)

see [stackexchange](https://quantumcomputing.stackexchange.com/questions/11810/ms-quantum-katas-measurements-task-2-3-problems-in-understanding-the-solutio)

4. From M' on the math is clear, but not the q# coding. Where do the X(q) and CNOT(a, q) come from? I cannot discover this in your mathematical explanation?

Thank you very much for enlighten me :)

BR
Markus

**Comment by mbuchberger1967** [comment]
I thought I could use Markdown to describe the matrices, I try it an other way....

**Comment by tcNickolas** [comment]
No, GitHub doesn't support LaTeX, you can do the formulas only using Unicode or screenshots.

This problem (and the explanation) was actually written by @martinquantum, so I'm afraid I can't really enlighten you on it. @martinquantum, could you address this question?

**Comment by mbuchberger1967** [comment]
Hi Mariia, thx for the quick response. I thought you would know it as I found this link to a paper where you and martin are named as the authors 
[](https://assets.codeforces.com/rounds/1116/contest-editorial.pdf)
@martinquantum : maybe you can help me with this?

**Comment by mbuchberger1967** [comment]
Hi @tcNickolas , @martinquantum 
I have an additional question. Meanwhile I can understand how you constructed M'. And if we use 1/sqrt(3) instead 1/sqrt(2) the matrix is unitary.
At the end you state:
![grafik](https://user-images.githubusercontent.com/25125667/82160605-e607ab00-9896-11ea-8dc9-4cd36b1bf3c3.png)

5. How can this matrix be a rotation around the y-axis if 
![grafik](https://user-images.githubusercontent.com/25125667/82160646-194a3a00-9897-11ea-8d39-bd5efc61d363.png)

Thx

**Comment by tcNickolas** [comment]
I finally got the time (and the right tools!) to sit down and dig into this question. Using the new [DumpOperation functionality](https://github.com/microsoft/Quantum/blob/main/samples/diagnostics/dumping/Dumping%20States%20and%20Operations.ipynb) I could just check which parts of the code correspond to which matrices without doing matrix multiplication manually.

The matrix in question is implemented using not a single controlled Ry gate, but rather a controlled Ry gate *plus some row/column reordering*, which was (rather inconveniently) omitted in the writeup. The following sequence of gates

    CNOT(a, q);
    X(q);
    (ControlledOnInt(0, Ry))([a], (-2.0 * alpha, q));

gives us exactly the matrix we're looking for

![image](https://user-images.githubusercontent.com/10113024/94190741-6059c480-fe61-11ea-8e23-bed2a74168a1.png)

The key here is to get the right matrix elements and then the right reordering of them.

(Apologies for taking so long - the answer three months after the question is probably not very helpful!)

**Comment by tcNickolas** [comment]
I sent a pull request to add this clarification to the workbook - omitting such information is indeed confusing, and we don't yet have a kata that would cover applying row/column permutations, so there is no place to look it up.

**Comment by mbuchberger1967** [comment]
It is still helpful, thank you.
