### ISSUE TITLE
Quantum NN vs Quantum-Inspired NN

### ISSUE THREAD

**Issue by vcjob** [microsoft/QuantumKatas#361]
Hello everyone! 

I know that it's kinda not the right place for that question, but I don't really know where else I can ask it. So I apologize beforehand. 
I can't find the true difference between Quantum Neural Network (QNN) and Quantum-Inspired Neural Network (QINN). 
I have multiple guesses: 
1. QINN and QNN are absolutely the same thing (all QNNs are actually QINNs unless the true quantum computing hardware is developed)
2. QINNs are the neural nets ensembles. 
3. Something else... ?

Thank you a lot for any information! Sorry again for asking it here.

**Comment by tcNickolas** [comment]
The best place for this kind of quantum computing questions is https://quantumcomputing.stackexchange.com/, so I would recommend you to post this question there. The Quantum Katas are still some time away from featuring either QNN or QINN :-)

**Comment by MrFa1n** [comment]
I can't find the true difference between Quantum Neural Network (QNN) and Quantum-Inspired Neural Network (QINN).
I have multiple guesses:

1. QINN and QNN are absolutely the same thing (all QNNs are actually QINNs unless the true quantum computing hardware is developed)
2. QINNs are the neural nets ensembles.
3. Something else... ?
Unfortunately, we don’t have time to think, can we get a short answer?

**Comment by MrFa1n** [comment]
> The best place for this kind of quantum computing questions is https://quantumcomputing.stackexchange.com/, so I would recommend you to post this question there. The Quantum Katas are still some time away from featuring either QNN or QINN :-)

I can't find the true difference between Quantum Neural Network (QNN) and Quantum-Inspired Neural Network (QINN).
I have multiple guesses:

QINN and QNN are absolutely the same thing (all QNNs are actually QINNs unless the true quantum computing hardware is developed)
QINNs are the neural nets ensembles.
Something else... ?
Unfortunately, we don’t have time to think, can we get a short answer?
