### ISSUE TITLE
Error parsing boolean value. Path '', line 1, position 1. when running first execution

### ISSUE THREAD

**Issue by akshajgaur** [microsoft/QuantumKatas#368]
Whenever, I have been running the first cell in the tutorials, I have been getting this error. 

Error parsing boolean value. Path '', line 1, position 1.

I can still check by algorithms with the reference implementation, but I can't run any exercises due to the syntax errror. 

I think the problem is that I have an updated version of IQSharp, but even when I change the cell, I get the same error.

**Comment by tcNickolas** [comment]
That's a new and interesting error. Can you provide your environment details? OS, .NET Core version, IQ# version installed, which tutorial you're running, a screenshot of the error?

**Comment by akshajgaur** [comment]
Nevermind, it was a small mistake. Thank you though!

**Comment by tcNickolas** [comment]
My favorite kind of issues :-)
