### ISSUE TITLE
Shor's algorithm kata

### ISSUE THREAD

**Issue by lmrazorea** [Microsoft/QuantumKatas#37]
Hi,

I've started work on creating a kata for Shor's algorithm.  Is it possible to update the corresponding item on the roadmap to show that it's being currently developed?

Thank you!

**Comment by tcNickolas** [comment]
Sure, I'll update it later today.

Do you want to share your thoughts about the breakdown into tasks for it? It's an ambitious topic, I was thinking that it would rely on several other, simpler katas, like quantum arithmetic.

**Comment by lmrazorea** [comment]
At the moment, my idea is to split the algorithm into the following major steps that will become kata tasks:
1) find appropriate coprime of the number that needs to be factorized;
2) generate the specific function involving the coprime that's mentioned in Shor's algorithm;
3) write the order finding oracle;
4) find the period of the function mentioned at 2) (maybe I'll be able to split this step into several tasks);
5) find factorization based on the computed period.

From looking at the existing kata sizes and their corresponding algorithms, I would say that Shor's kata will be around 400+ lines of code.
Your suggestion about making more than one kata to accomplish this might be the right thing to do.
I'm thinking to work on finishing the implementation as one kata, for now, so I get a complete picture of the end result. And then look at splitting it into multiple katas.
