### ISSUE TITLE
Conversion Question

### ISSUE THREAD

**Issue by jainvasu631** [microsoft/QuantumKatas#374]
How to convert LittleEndian into an Array of Qubits

**Comment by tcNickolas** [comment]
`LittleEndian` is a wrapper type around the `Qubit[]` type, so to treat it as a `Qubit[]` you need to unwrap it: `Length(register!)` to get the number of qubits or `register![i]` to get i-th qubit. You can read more about the "unwrap" operator ! in [this section of the docs](https://docs.microsoft.com/en-us/quantum/user-guide/language/types#access-anonymous-items-with-the-unwrap-operator).
