### ISSUE TITLE
Tutorials - SingleQubitGates - Exercise 2 - GlobalPhaseI

### ISSUE THREAD

**Issue by theRomanMercury** [microsoft/QuantumKatas#382]
Hello,

I tried to solve 

// Exercise 2.
    operation GlobalPhaseI (q : Qubit) : Unit is Adj+Ctl {
        // ...
 }
    

    

with this code 

    namespace _2 {
    open Microsoft.Quantum.Intrinsic;
    open Microsoft.Quantum.Canon;
    open Microsoft.Quantum.Measurement;
    
    operation Apply() : Result {

        using (qubit = Qubit()) {
        
              X(qubit);
              Z(qubit);
              Y(qubit);

            let result = M(qubit);

            return MResetX(qubit);
        }
    }

     @EntryPoint()
    operation RunProgram() : Unit {
        

        Message($"Apply");

        for (idx in 0..10) {
            let (result) = Apply ();
            Message($"Measured and observed ({result}).");
        }
    }
}

And I got this result 

Apply
Measured and observed (One).
Measured and observed (One).
Measured and observed (Zero).
Measured and observed (One).
Measured and observed (One).
Measured and observed (Zero).
Measured and observed (One).
Measured and observed (Zero).
Measured and observed (One).
Measured and observed (One).
Measured and observed (Zero).

Is it true and is there a way to write shorter ?

**Comment by tcNickolas** [comment]
Answered the question at https://quantumcomputing.stackexchange.com/questions/12604/quantum-katas-tutorials-singlequbitgates-exercise-2-globalphasei/12608#12608.
