### ISSUE TITLE
Error updating the kata

### ISSUE THREAD

**Issue by BrokenDuck** [microsoft/QuantumKatas#399]
I updated the kata with the instruction but when from version 0.11.2003.3107 to 0.12.20070124 but when I run the same code in the new notebook (after having updated iqsharp and installed it again) it returns `Could not load file or assembly 'Microsoft.Quantum.Standard, Version=0.11.2003.3107, Culture=neutral, PublicKeyToken=40866b40fd95c7f5'. The system cannot find the file specified.`

**Comment by tcNickolas** [comment]
Looks like there are still some binary leftovers from the previous version. Can you try deleting `bin` and `obj` folders and running the notebook again?

**Comment by BrokenDuck** [comment]
Thanks, for the answer, had this problen before and I forgot how I fixed it.
