### ISSUE TITLE
Unicode nit

### ISSUE THREAD

**Issue by Quuxplusone** [Microsoft/QuantumKatas#4]
At least BasicGates/Tasks.qs, but probably all of the code files, use a mix of two different Unicode characters to represent the ">"-looking symbol:
```
+++
⟩ U+27E9 MATHEMATICAL RIGHT ANGLE BRACKET
〉 U+232A RIGHT-POINTING ANGLE BRACKET
+++
```
At least in my browser, U+232A isn't even the same width as the other characters in the monospace font, which makes the discrepancy really obvious and distracting.
It would be nice to go through and find all instances of U+232A and replace them with U+27E9.

**Comment by tcNickolas** [comment]
@Quuxplusone Thank you again for noticing and fixing this. I wonder what browser did you use for discovering this? None of the browsers and text editors I've tried shows any difference between the characters, and I'd like to prevent U+232A from creeping in the code again.

**Comment by Quuxplusone** [comment]
I see it in every application I've tried. Safari and Chrome (using Monaco font, maybe?) both show the difference. Terminal (using Menlo Regular 13pt) shows the difference.

However, I might have an explanation at least for the browsers. I think what might be happening is that one of the characters is supported by many fonts, and the other is not supported by many fonts; therefore the browser/terminal/etc. is falling back onto a version of the unsupported character in a *different font*.  I'd be very surprised if this were happening in Terminal, though.

![Terminal, using Menlo Regular 13pt](https://i.imgur.com/mA1dUOT.png)

"Everson Mono" and "FreeSerif" seem to be fonts where both characters are supported, with differing glyphs:
http://www.fileformat.info/info/unicode/char/27E9/fontsupport.htm
http://www.fileformat.info/info/unicode/char/232A/fontsupport.htm

If you want to prevent U+232A from creeping back into the code, may I recommend `grep` plus a git commit hook. :)
