### ISSUE TITLE
Exception Microsoft.Quantum.Simulator.Runtime.dll

### ISSUE THREAD

**Issue by charly37** [Microsoft/QuantumKatas#41]
Hi,

I followed the instructions here
https://www.microsoft.com/net/download/linux-package-manager/ubuntu18-04/sdk-current
https://docs.microsoft.com/en-us/quantum/install-guide/command-line?view=qsharp-preview

but had issue on various linux versions (you can reproduce with ubuntu:18.04 or centos:7 from dockerhub) with the following error

```
Unhandled Exception: System.DllNotFoundException: Unable to load shared library 'Microsoft.Quantum.Simulator.Runtime.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libMicrosoft.Quan
tum.Simulator.Runtime.dll: cannot open shared object file: No such file or directory
   at Microsoft.Quantum.Simulation.Simulators.QuantumSimulator.Init()
   at Microsoft.Quantum.Simulation.Simulators.QuantumSimulator..ctor(Boolean throwOnReleasingQubitsNotInZeroState, Nullable`1 randomNumberGeneratorSeed, Boolean disableBorrowing)
   at Microsoft.Quantum.Examples.Teleportation.Program.Main(String[] args) in /Quantum/Samples/Teleportation/Program.cs:line 13
```

The following SO issue help me fixing it (https://stackoverflow.com/questions/49579153/unable-to-load-dll-microsoft-quantum-simulator-runtime-dll) by installing libgomp1

Maybe there is a way to improve the framework or mention this dependency somewhere in the doc.

**Comment by tcNickolas** [comment]
Thank you for reporting this!

I've transferred this issue to the documentation repo https://github.com/MicrosoftDocs/quantum-docs-pr/issues/335, since it's not really something that can be addressed on the katas project level.
