### ISSUE TITLE
[DistinguishUnitaries] Kata : Add Problems from Q# Summer 2020 Contests

### ISSUE THREAD

**Issue by jainvasu631** [microsoft/QuantumKatas#415]
The DistinguishUnitaries Kata doesn't currently have all the problems from Microsoft Q# Summer 2020 [Warmup Contest](https://codeforces.com/contests/1356) and [Main Contest](https://codeforces.com/contest/1357). Should we add them to this Kata?

If so, I wouldn't mind working on adding the problems as new Tasks.

**Comment by tcNickolas** [comment]
Yes, I need to add them - I have them in Kata format already (that's my default development format for the new tasks), it's a matter of me sitting down and adding them to the already existing tasks. I should be able to get to it some time next week.
