### ISSUE TITLE
Some matrices in Workbook_MultiQubitGates.ipynb are not diplayed properly

### ISSUE THREAD

**Issue by zegman** [microsoft/QuantumKatas#458]
Some of the matrices in Workbook_MultiQubitGates.ipynb are not displayed properly:
![image](https://user-images.githubusercontent.com/1073364/90014471-caeae280-dcaf-11ea-8539-523fe0d89d60.png)

**Comment by tcNickolas** [comment]
That's odd, I just double-checked them and they look as expected to me (exercise 1 I'm assuming):
![image](https://user-images.githubusercontent.com/10113024/90044284-4b92ea00-dc82-11ea-91bb-d6792ae84942.png)

What kind of environment are you using? We've had reports of the math in the notebooks rendering incorrectly in VS Code (#313) and I think the consensus was that VS Code support for notebooks is not mature enough to support our notebooks yet.

**Comment by zegman** [comment]
This is indeed exercise 1.
This is happening in chrome and Safari on Mac.

**Comment by tcNickolas** [comment]
Hmm, I don't have easy access to a Mac to reproduce... Can you try to find a way to fix the display? If you do and send a PR, we'll be able to check that it doesn't break display in other environments easily.

**Comment by zegman** [comment]
I looked at the code, and couldn't figure out why it renders this way.
To be clear, this happens when pointing the above mentioned browsers on mac to: https://github.com/microsoft/QuantumKatas/blob/master/tutorials/MultiQubitGates/Workbook_MultiQubitGates.ipynb

**Comment by zegman** [comment]
I now checked, and the same happens on Chrome using Windows 10.

**Comment by tcNickolas** [comment]
Ah, you're looking at them on GitHub! GitHub's rendering of the math notebooks is very basic, so it's not going to render properly no matter what we do :-) 

The intended way to use the notebooks is to run them using "jupyter notebook" command from command line (you need to install Jupyter and IQ#, as the installation guide suggests). Alternatively, you can use the zero-install version at https://mybinder.org/v2/gh/Microsoft/QuantumKatas/master?filepath=index.ipynb which can be a bit slower and doesn't preserve the state between runs, but is a good way to take a quick look.

**Comment by zegman** [comment]
OK - thanks.
I will close this.
