### ISSUE TITLE
Possible Documentation Error

### ISSUE THREAD

**Issue by Manvi-Agrawal** [microsoft/QuantumKatas#466]
At **_line 158_** in _**utilities/Microsoft.Quantum.Katas/KataMagic.cs**_, the documentation of **Simulate** function describes calling **FindRawAnswer** function. But in the implementation of Simulate function **FindRawAnswer** hasn't been used; instead **FindSkeltonAnswer** is used. 
 
       155. /// <summary>
       156. /// Executes the given kata using the provided <c>userAnswer</c> as the actual answer.
       157. /// To do this, it finds another operation with the same name but in the Kata's namespace
       158. /// (by calling FindRawAnswer ) and replace its implementation with the userAnswer
       159. /// in the simulator.
       160. /// </summary>
       161. /// public virtual bool Simulate(OperationInfo test, OperationInfo userAnswer, IChannel channel)
       162. {
       163.    var skeletonAnswer = FindSkeletonAnswer(test, userAnswer);
                  ...
                  ...
                  ...
       200. }

**Comment by tcNickolas** [comment]
There is a discrepancy indeed - I suspect `FindSkeletonAnswer` used to be called `FindRawAnswer` at some point in the past. Would you be willing to send a PR with this fix? If not, I'll get to it at some point.

Thank you!

**Comment by Manvi-Agrawal** [comment]
@tcNickolas I would be willing to work on the issue
