### ISSUE TITLE
Create troubleshooting guide

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/QuantumKatas#476]
There is a set of "standard" things that can go wrong when running the katas, and it makes sense to write them down in a single place, so that a new user has an easy place to start troubleshooting their issue.

Here are a few examples that come to mind; let's think whether we can come up with more.

* "Syntax does not match any known patterns" when executing notebooks: check that you've executed `%package` cell and it has the right version in it
* "Invalid test name" when executing notebooks: check that you've executed `%workspace reload` cell
* Failures if IQ# is not installed (notebook treated as Python)
* Failures if extra Python modules are not installed for Python notebooks that require them
* Math expressions not rendered properly in notebooks: check that you're not viewing the notebooks on GitHub (#458) or in VS Code (#313)

**Comment by vivanwin** [comment]
I can get started with this.

**Comment by tcNickolas** [comment]
We will be migrating the Katas to the new QDK that will use a different infrastructure (see https://devblogs.microsoft.com/qsharp/introducing-the-azure-quantum-development-kit-preview/ for the announcement). This is going to change pretty much everything about troubleshooting the local setup of the repo (starting with it being at https://github.com/microsoft/qsharp), and the online version won't have any missing components to troubleshoot. I don't think it makes sense to work on the troubleshooting for the old QDK, so closing this issue as "won't fix".
