### ISSUE TITLE
Create Measurements tutorial

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/QuantumKatas#484]
This tutorial should fill the space between the Superposition kata and the Measurements kata: assuming that the learner is already familiar with the previous topic (i.e., is comfortable with the Dirac notation, the concept of superposition and using quantum gates), introduce the necessary concepts and Q# constructs to use measurements.

Here is the tutorial structure I have in mind (we could frame them as two separate tutorials, similar to SingleQubitGates and MultiQubitGates).

**Part 1. Measuring single-qubit systems**

* Measuring a single qubit in computational basis, outcomes and their probabilities
* An exercise to calculate the probability of getting a specific outcome when measuring a given state (something like 0.6|0⟩ + 0.8|1⟩). It's somewhat pointless to implement in Q# so we could do something similar to exercise 1 in MultiQubitSystems - a pen and paper exercise with an answer to check yourself under the `<details>` tag.
* Expressing the measurement in computational basis in Q# using M
* Using measurements to distinguish single-qubit states
* Programming exercise: distinguish |0⟩ from |1⟩ (similar to the first task in the Measurements kata)
* Measuring a single qubit in a different Pauli basis (using |+⟩, |-⟩ Pauli X basis as an example)
* Math insert: representing measurements as projectors (in Dirac notation and in matrix notation)
* A note on non-observability of global phase
* A pen-and-paper exercise to compute the probabilities (similar to previous one)
* Expressing different types of measurements in Q# using Measure
* Several exercises with different bases (Pauli Y and some non-Pauli basis)

**Part 2. Measuring multi-qubit systems**

* Measuring all qubits in computational basis (one by one, not joint measurement)
* Programming exercise: given array of qubits in a basis state, read out and return the basis state
* Partial measurements, probabilities of outcomes, partial system collapse (Dirac notation is going to work nicely here)
* Programming exercise
* Joint measurements of multiple qubits
* Programming exercise

This is an ambitious issue, so feel free to start in increments: the first portion can be the first part up to the programming exercise on distinguishing |0⟩ from |1⟩.

**Comment by tcNickolas** [comment]
(I think I know somebody who is interested, putting this on hold until I can confirm)

**Comment by PratikSathe** [comment]
I will work on this.
