### ISSUE TITLE
[CHSHGame/GHZGame] Repeat randomized tests multiple times

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/QuantumKatas#492]
Tasks 2.2 and 2.4 in [CHSHGame kata](https://github.com/microsoft/QuantumKatas/blob/main/CHSHGame/Tests.qs) and 2.2 in [GHZGame kata](https://github.com/microsoft/QuantumKatas/blob/main/GHZGame/Tests.qs) can have incorrect solutions (for example, measuring in incorrect basis) that still could pass the tests with non-negligible probability. It would make sense to repeat the test (the operations inside the `using` block) several times to reduce the probability of the tests giving false positive verdict.

**Comment by ziqi-ma** [comment]
Why is this possible? I'm assuming the simulator uses state vectors, and if the adjoint of reference cancels implemented solution then the answer must be correct?
