### ISSUE TITLE
[Graph Coloring] Trouble understanding oracle

### ISSUE THREAD

**Issue by BrokenDuck** [microsoft/QuantumKatas#496]
Hello, I am troubled by the oracle proposed as a solution in the Graph Coloring Kata. The `ColorEqualityOracle_Nbit` operation applies the X gate if both colors are equal. This means the "conflicts" qubit array would be equal to |1...1⟩ if all the colors are equal, right ? Then why are we using 0 in `ControlledOnInt(0, X)(conflicts, target)`. Shouldn't it be a 1 ? Thanks for the read, I probably already understood this, however I can't remember.

**Comment by tcNickolas** [comment]
`ColorEqualityOracle_Nbit` flips the target qubit if the colors are equal. For `VertexColoringOracle`, the cases when the colors are equal make the coloring invalid, so to mark the coloring as valid we want no pair of colors to be equal - all qubits in `conflicts` should be in |0⟩ state for the target qubit to be flipped (think of it as "there should be no conflicts"), marking the coloring as valid. `ControlledOnInt(0, X)` does exactly that.

No worries, sometimes looking at a task I haven't seen for a while gives me pause too :-)

**Comment by BrokenDuck** [comment]
Of course ! I am feeling pretty dumb right now. Thanks for reminding me what the goal is 😁.
