### ISSUE TITLE
[Contribution guide] Add more detailed instructions on adding content

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/QuantumKatas#497]
[Contribution guide](https://github.com/microsoft/QuantumKatas/blob/main/.github/CONTRIBUTING.md) lists the types of things one could contribute, but doesn't go into details on the moving pieces that go into doing each of those things. It makes sense to add a bit more guidance on this:

* Section "Improving Existing Katas" should really be called "Adding New Tasks to Existing Katas"; #177 is an example pull request that touches all 4 files that need to be modified and includes task and test renumeration to accommodate the new task in the middle of the sequence. 
* Section "Contributing New Katas" could have just an example of a pull request, such as #378.
* A new section "Contributing Workbooks" could have a paragraph on what are the workbooks (can take one from any workbook introduction) and a link to an example, such as #377.

**Comment by jainvasu631** [comment]
@tcNickolas 
I have a few suggestions based on my experience contributing  for whoever works on this Issue. 
**Tutorial vs Kata**
I felt that the difference between a tutorial and a normal Kata should be present in the contributions guide. While writing a tutorial an author needs to take into account the prior information or content the reader has consumed as well as the fact the reader may be novice and hence certain explanations and tasks must be geared towards him even if they seem blindly obvious to the author.

**Writing Workbooks**
The references solutions are go-to sources for strategy/algorithms and code while writing Workbooks. However authors must also realize that they are free to contribute their own solutions as well. Sometimes, they may come up with a new solution which  can be included if its simpler/more concise/more readable or employs a markedly different strategy than the reference solution. This is subjective to a large extent but not entirely infrequent.
