### ISSUE TITLE
[SolveSATWithGrover] Refactor tests for 1.6 and 2.2 to run faster

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/QuantumKatas#507]
Currently the tests for tasks [1.6](https://github.com/microsoft/QuantumKatas/blob/main/SolveSATWithGrover/Tests.qs#L264) and [2.2](https://github.com/microsoft/QuantumKatas/blob/main/SolveSATWithGrover/Tests.qs#L330) generate the SAT instances randomly, with up to 7 variables and 14 clauses, which can cause significant test slowdown if several tests are generated on the larger side (the more variables and clauses the test has, the longer it runs). 

It makes sense to refactor the tests so that they run faster without loss of coverage.

1. Task 1.6 doesn't really need to spend that much time on 2-SAT instances (that's an artifact left from before when task 1.5 was dealing not with an individual clause but with 2-SAT problem instead), so we can replace `Run2SATTests` with `RunCrossTests` which only include OR, XOR and AlternatingBits oracles, and drop the random 2-SAT test instances.
2. Both tasks 1.6 and 2.2 should generate the SAT instances more deterministically (though we don't need them to be 100% deterministic). I would modify `Generate_SAT_Instance` to take two parameters - the number of variables and the number of clauses - and pass them manually from the test so that we can have a fixed distribution of tests in each run. I would also reduce the number of tests - maybe one random test for each of 3 .. 6 variables for task 1.6 and one random test for each of 2 .. 6 variables for task 2.2. (I would also rename `Generate_SAT_Instance` to `GenerateSATInstance`, since here the underscores don't carry any particular meaning.)

**Comment by sgalpha01** [comment]
Hey @tcNickolas, can you please assign this issue to me? It would be my good first issue in this topic. Also, I may need a bit of help as I am a beginner.
