### ISSUE TITLE
QuantumClassification tutorials don't work when using Docker image (e.g., Binder)

### ISSUE THREAD

**Issue by rmshaffer** [microsoft/QuantumKatas#511]
Example: Open the "InsideQuantumClassifiers" tutorial on Binder:
https://mybinder.org/v2/gh/Microsoft/QuantumKatas/main?filepath=tutorials/QuantumClassification/InsideQuantumClassifiers.ipynb

When executing the third cell, the following error appears:
```
/snippet_.qs(4,6): error QS6104: No namespace with the name "Microsoft.Quantum.MachineLearning" exists.
/snippet_.qs(15,29): error QS5022: No identifier with the name "InputEncoder" exists.
```

I believe this is because the [`Dockerfile`](https://github.com/microsoft/QuantumKatas/blob/main/Dockerfile) currently doesn't pre-build any Katas that depend on `Microsoft.Quantum.MachineLearning`, which means that package does not get downloaded and cached in the image. Since the `Dockerfile` then disables all NuGet package downloading, the package cannot be retrieved at runtime.

I expect the fix for this is just to add a command to the `Dockerfile` something like:
```
./scripts/prebuild-kata.sh tutorials/QuantumClassification InsideQuantumClassifiers.ipynb
```

**Comment by tcNickolas** [comment]
Good catch! Binder execution of this kata is rather slow, so I've been treating it as a read-only (and only checking that it works locally). 

The fix might need a bit of experimentation: `./scripts/prebuild-kata.sh` might be rather slow and time out Binder builds. When this tutorial was standalone, [RUN dotnet build QuantumClassification](https://github.com/microsoft/MLADS2020-QuantumClassification/blob/master/Dockerfile#L22) in the Dockerfile was sufficient to keep the Binder functional, but we'll need to double-check this.

I won't get to it in the next couple of weeks, so marking this as up for grabs.

**Comment by rmshaffer** [comment]
@tcNickolas That's a good point. In fact, I believe just `RUN dotnet restore QuantumClassification` would be all that's needed for the packages to get cached in the image and therefore for the notebook to work properly.
