### ISSUE TITLE
In the Linear Algebra tutorial, its says Matrices are 0-indexed, but most books have them 1-indexed.

### ISSUE THREAD

**Issue by lwoodyiii** [microsoft/QuantumKatas#514]
In Part I. Matrices and Basic Operations - Matrices and Vectors
It says:
 _𝐴𝑖,𝑗  refers to the element in row  𝑖  and column  𝑗  of matrix  𝐴  **(all indices are 0-based)**. In the above example,  𝐴0,1=2 ._

But Wikipedia says:

The individual items in an m×n matrix A, often denoted by ai,j, where i and j usually vary from 1 to m and n, respectively, are called its elements or entries.
https://en.wikipedia.org/wiki/Matrix_(mathematics)

This is from Wolfram MathWorld (https://mathworld.wolfram.com/Matrix.html)
![image](https://user-images.githubusercontent.com/1810351/95274457-eb4c9e80-0813-11eb-856f-960a43e51338.png)

Mike and Ike also uses 1-indexed matrices.

**Comment by tcNickolas** [comment]
That really depends on the convention. In programming (in most modern languages... not talking about Fortran) arrays typically use 0-based indices, and since this tutorial is heavily on programming, we chose to use 0-based indices to match the notation.

**Comment by lwoodyiii** [comment]
You're right :) Sorry about that. I was thinking from just a math perspective. I didn't think from a programming perspective. Indeed, numpy uses 0 based indexing for their matrices. Taking Linear Algebra this semester, so have math on the brain :)
