### ISSUE TITLE
Replace CounterSimulator with QuantumSimulator where possible

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/QuantumKatas#518]
In #478 we migrated to the new way of marking Q# unit tests using `@Test` attribute (compared to the old way that involved a C# wrapper calling certain Q# operations). This means that we're no longer restricted by the inconvenience of directing different tests in one kata to run on different simulators. In multiple cases there are only one or two tasks in a kata which require `CounterSimulator`, the rest can be executed on `QuantumSimulator`.

We can use this to check which tasks actually require counting operations or allocated qubits and which tasks don't, and migrate the ones that don't require either from `@Test("Microsoft.Quantum.Katas.CounterSimulator")` to `@Test("QuantumSimulator")`.

Here is an approximate list of the katas and tutorials with tasks that can be migrated:
* [ ] DeutschJozsaAlgorithm, oracle tasks.
* [ ] GraphColoring
* [ ] JointMeasurements
* [ ] PhaseEstimation
* [ ] QEC_BitFlipCode
* [ ] RippleCarryAdder
* [ ] SimonsAlgorithm, oracle tasks
* [ ] TruthTables
* [ ] ExploringDeutschJozsaAlgorithm tutorial, oracle tasks

**Comment by Manvi-Agrawal** [comment]
@tcNickolas, I would like to work on this issue.

**Comment by vivanwin** [comment]
Hi @Manvi-Agrawal,

Great to hear, go ahead! If you have any questions don't hesitate to ask.
