### ISSUE TITLE
Specify the task1 of TruthTable kata clearly in qsharp and jupyter frontend

### ISSUE THREAD

**Issue by Manvi-Agrawal** [microsoft/QuantumKatas#522]
Currently, the Truth Tables kata asks learner to define two new truth tables x2 and x3, but the intention is not clearly specified. 

Therefore some description can be added, specifying that :<br>
x2 should be true for : 010,011,101,110
x3 should be true for : 100,101,110,111

**Comment by Manvi-Agrawal** [comment]
Would be happy to send in a fix.

**Comment by msoeken** [comment]
I think that this would give away too much information. The task states that `x2` and `x3` are projective functions for elementary variables, and provides the on-set for `x1` as an example. The readers of this task should determine the on-sets should determine the on-sets for `x2` and `x3` themselves. One might point to the `x2` column in the table above as a hint.

**Comment by Manvi-Agrawal** [comment]
Thanks @msoeken for the clarification

**Comment by Manvi-Agrawal** [comment]
Hi, @msoeken @tcNickolas , I was thinking if we could add a couple of new tasks in Truth Tables kata. 
Honestly I was confused about the intension of task1. From the example in the explaination of truth table of  (x1 AND x2), I was expecting a similar kind of task, ie ( (x1 AND x2 AND x3), (x1 AND x2 AND x3) or any descriptive task like either one of x1,x2 and x3 is true). 

Also, I felt example of x1 to be a bit misleading. In theory we were mentioning projective functions, f as a mapping from n-inputs to a single output. So, I misunderstood first task as the 
Given : x1 should be true for : 001,011,101,111
Goal : To specify the truth table for x1 in binary form.

Some of the new tasks which I think can be added 
- Specify truth table for 3-bit input function (x1 AND x2 AND x3)
- Specify truth table for 3-bit input function if exactly 1 bit out of x1, x2 or x3 is true
- Specify truth table for 3-bit input function if exactly 2 bits out of x1, x2 or x3 is true

**Another suggestion**
Also, I think it would be nice if we could explain AND, OR, XOR to the learner by providing the truth tables for 2 bits instead of just asking them to use the bitwise operators. Although, I am not sue whether we wuld want to do this in the Truth Tables kata, since katas are supposed to provide high level implementation. What are your about making a tutorial for the same?

**Comment by msoeken** [comment]
Hi @Manvi-Agrawal. I think the two tasks you are mentioning is interesting. I don't quite agree with explaining AND, OR, and XOR as 2-input truth tables instead of the bitwise operators. These are two different things. For the latter, we perform the AND of the two truth tables, which is essentially performing the 2-input AND on each pair of bits. This can be done efficiently on an int by using bitwise operations.

**Comment by Manvi-Agrawal** [comment]
Hi @msoeken. Thanks for the compliment. Also, got the point of not explaining the truth tables of AND, OR and XOR as it would complicate the things for the learner.

**Comment by Manvi-Agrawal** [comment]
Hi @msoeken @tcNickolas, can I go ahead with adding these new tasks in the Truth Tables kata? Thinking of raising a new issue and raising a new PR for the same.

**Comment by tcNickolas** [comment]
@Manvi-Agrawal Are you thinking new tasks should be similar to the first task, so that the truth tables would have to be hardcoded rather than obtained by some manipulations from simpler ones like the later tasks? I agree, this could be helpful to practice converting truth tables to integers before we move on to manipulating those integers. Feel free to send a PR (well, probably after the CI build on this one finishes and we merge it - our CI has been slow today so it might take some time...)

**Comment by Manvi-Agrawal** [comment]
Hi @tcNickolas.  I like your suggestion to extend these two tasks so that they can be obtained by some manipulations from simple truth tables. I was thinking of new tasks so that truth tables would have to be hardcoded. So, maybe after the first task, learner can be asked to implement the these truth tables as hardcoded values. After learning the AND, OR, XOR,NOT, and if then else, the learner can be encouraged to do the same tasks using the TTOr operation.<br>
Also, I am hoping to finish this task by the end of month since I have a couple of pending items.

**Comment by tcNickolas** [comment]
These specific tasks look like they'd be easier done hardcoded than using elementary operations, so I'd probably just keep them hardcoded.

Sure, no rush - I have plenty of reviews to catch up on! (not to mention everything else...)

**Comment by Manvi-Agrawal** [comment]
Sounds good
