### ISSUE TITLE
Fail to import Microsoft..Quantum.Standart.Visualisation during merge pipeline tests of notebooks

### ISSUE THREAD

**Issue by BrokenDuck** [microsoft/QuantumKatas#526]
Hi, I recently finished the graph coloring notebook and created a pull request. However, the pipeline tests fail for the notebook part 2 job (Validate notebook part ) for Linux, Windows and mac OS. Particularly, when it runs the notebook with iqsharp, it fails to import `'Microsoft.Quantum.Standard.Visualization'` because it cannot find `/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/nbconvert/filters/highlight.py:147`. This happens with every  workbook. Sadly, I do not know how to resolve this issue. Any help is appreciated.

Here are the error logs : [Linux](https://dev.azure.com/ms-quantum-public/9af4e09e-a436-4aca-9559-2094cfe8d80c/_apis/build/builds/15806/logs/77), [Windows](https://dev.azure.com/ms-quantum-public/9af4e09e-a436-4aca-9559-2094cfe8d80c/_apis/build/builds/15806/logs/97) and [mac](https://dev.azure.com/ms-quantum-public/9af4e09e-a436-4aca-9559-2094cfe8d80c/_apis/build/builds/15806/logs/81)
Pipelines page : [here](https://dev.azure.com/ms-quantum-public/Microsoft%20Quantum%20(public)/_build/results?buildId=15806&view=results)

**Comment by tcNickolas** [comment]
The failure to import `Microsoft.Quantum.Standard.Visualization` is a red herring here - you'll see that in successful runs as well. There are some nuances in loading the packages that we introduced in https://github.com/microsoft/QuantumKatas/pull/515 which mean that by the time the notebooks try to load that package, NuGet package loading is disabled. 

Looking at the logs, it looks like the actual error comes from trying to execute `%package Microsoft.Quantum.Katas::0.12.20082513` - we have updated the version to the latest QDK earlier this week (in https://github.com/microsoft/QuantumKatas/pull/468) and removed the `%package` cells; if you remove that, that error should be fixed.

**Comment by BrokenDuck** [comment]
@tcNickolas  So I simply delete the "init" cell ?

**Comment by rmshaffer** [comment]
@BrokenDuck yes, you should delete the cell containing `%package Microsoft.Quantum.Katas::0.12.20082513` and the associated instructions.

**Comment by tcNickolas** [comment]
Looks like in the latest PR this is resolved, so I'm closing this issue.
