### ISSUE TITLE
Switch from CounterSimulator.GetMaxQubitCount to AllowAtMostNQubits

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/QuantumKatas#544]
**Context**

Currently we implement the tests for the tasks that restrict the number of qubits the solution can allocate using a custom simulator `CounterSimulator`, which offers [several counting operations](https://github.com/microsoft/QuantumKatas/blob/main/utilities/Common/Utils.qs), in particular `ResetQubitCount` and `GetMaxQubitCount`. 

**Improvement**

We should be able to use the recently introduced library operation [AllowAtMostNQubits](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.diagnostics.allowatmostnqubits) instead, and use the regular `QuantumSimulator` instead. The affected katas are:

* [ ] GraphColoring, task 1.5
* [ ] RippleCarryAdder, task 3.5
* [ ] PhaseEstimation, tasks 2.1 and 2.2
(In task 2.1 the test also uses `GetOracleCallsCount` operation, which should be possible to replace with [AllowAtMostNCallsCA](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.diagnostics.allowatmostncallsca) - needs some experimentation.)

This needs some careful testing to make sure the correct solutions passe and allocating extra qubits fails.

**Example**
In GraphColoring task, for example, [task 1.5 check](https://github.com/microsoft/QuantumKatas/blob/main/GraphColoring/Tests.qs#L141) should look something like this:

```qsharp
within {
    AllowAtMostNQubits(2*N+1, "You are not allowed to allocate extra qubits.");
} apply {
    CheckColorEqualityOracle(N, ColorEqualityOracle_Nbit);
}
```

Feel free to target one test at a time!

**Comment by JimmyHamel** [comment]
I Would like to work on these! 

Also, while testing GraphColoring, task 1.5 using the reference implementation i got errors. It looks like either the solution allocated twice the qubits, or the current simulator counts double the qubits. 

Not sure if im doing something wrong but im copying : 
 within {
            for ((q0, q1) in Zip(c0, c1)) {
                // compute XOR of q0 and q1 in place (storing it in q1)
                CNOT(q0, q1);
            }
        } apply {
            // if all XORs are 0, the bit strings are equal
            (ControlledOnInt(0, X))(c1, target);
        }

Inisde   operation ColorEqualityOracle_Nbit located in Task.qs

and i get the following failed test doing dotnet test in the GrapColoring folder: 
 X T15_ColorEqualityOracle_Nbit_Test [80ms]
  Error Message:
   Microsoft.Quantum.Simulation.Core.ExecutionFailException : You are not allowed to allocate extra qubits maxcout 6 jsais paskoi 3. You allocated 3
        Expected:       3
        Actual: 6

I actually can only run the test by doing this in the test : 
            EqualityFactI(nq**/2**, 2*N+1, $"You are not allowed to allocate extra qubits maxcout {nq} jsais paskoi {2*N+1}. You allocated {nq - (2*N+1)}");

Any idea? 

I'll try to bypass this problem while testing my changes for now !

**Comment by tcNickolas** [comment]
I was literally just typing the message to ask whether you got the latest version :-)

**Comment by JimmyHamel** [comment]
haha yeah, my fault for writting comment at midnight :-) thanks for the quick answer tho! There is some tests that used the QuantumCounter to print the number of extra qubits that were used. Is that something that we want to loose using these new calls? or is there a way to fetch that information using AllowAtMostNQubits and  AllowAtMostNCallsCA?

**Comment by tcNickolas** [comment]
Good catch, I missed the second task in PhaseEstimation - yes, please!

**Comment by JimmyHamel** [comment]
on it! 
A little note on what im doing right now: the first 2 were pretty straightfoward, howerver im having issues with:  AllowAtMostNCallsCA. Right now im debuging without even considering the maxqubit constraint. 

My test are failing at : Test1BitPEOnOnePair(X, BoundCA([X, H]), -1); 

The framework output saysthat X is called more than once. It seems that for AllowAtMostNCallsCA(1, Controlled U, "You are allowed to call Controlled U exactly once"), ---- AllowAtMostNCallsCA does not see a difference between U and Controlled U. I might be doing something wrong on my side so i'll keep digging, but this is my conclusion as of right now.

**Comment by tcNickolas** [comment]
@cgranade Do you know whether AllowAtMostNCallsCA allows to differentiate between controlled and not-controlled variants of a unitary in this scenario?

**Comment by tcNickolas** [comment]
@JimmyHamel If AllowAtMostNCallsCA doesn't work in this scenario, I would switch just the qubit counting to AllowAtMostNQubits and leave operation counting as is, and probably file an issue on the libraries repo describing the behavior, similar to https://github.com/microsoft/QuantumLibraries/issues/343. We won't be doing a mass switch to AllowAtMostNCallsCA until that one is resolved, so it's ok to keep CounterSimulator here for now.

**Comment by JimmyHamel** [comment]
Sounds good! I'll keep the CounterSimulator for PhaseEstimation, tasks 2.1 only and change only the qubit counter part. 

I created an issue in the QuantumLibraries repo, you can find it here: https://github.com/microsoft/QuantumLibraries/issues/367 

thank you!

**Comment by JimmyHamel** [comment]
Related merge request: https://github.com/microsoft/QuantumKatas/pull/560
