### ISSUE TITLE
Create Oracles tutorial

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/QuantumKatas#551]
This tutorial should be the first in the "Quantum Oracles and Simple Oracle Algorithms" topic: assuming that the learner is already familiar with the previous topics (i.e., is comfortable with the Dirac notation, the concepts of superposition and measurements and using quantum gates), introduce the concept of quantum oracles, some simple tricks to implementing them and Q# exercises to internalize these topics.

Here are some things we need to cover in this tutorial:

* Phase oracles (definition, examples, exercises)
* Marking oracles (definition, examples, exercises)
* Defining oracles on basis states defines them on all other states
* We don't measure the state to apply an oracle to it!
* Converting marking oracles to phase oracles (a.k.a. “phase kickback trick”)

We're assuming that reversible computing (i.e., general techniques of implementing oracles) will be covered in a separate tutorial, so in this one we want to focus on the definition and the basics necessary to start working with the simple oracles for Deutsch-Jozsa algorithm (and a bit later Simon's and Grover's algorithms).

Here are some good resources to start with:
* [ExploringDeutschJozsaAlgorithm tutorial](https://github.com/microsoft/QuantumKatas/tree/main/tutorials/ExploringDeutschJozsaAlgorithm) which starts with a section on phase oracles and some examples/exercises on implementing them.
* [MS Learn module on Grover's search](https://docs.microsoft.com/en-us/learn/modules/solve-graph-coloring-problems-grovers-search/) has two units discussing oracles, including some Q# demos of oracles application ("before" and "after" states).
* [[oracles] tag](https://quantumcomputing.stackexchange.com/questions/tagged/oracles) on QuantumComputing Stackexchange shows a lot of confusion that people face when learning about the oracles and implementing them

**Comment by williamdolsen** [comment]
Hi, this is William Olsen and I will be creating a tutorial to encapsulate the requested information.  I will provide an introduction to quantum oracles, what they are, why they matter, and how to use them as well as different types of oracles.  Then the tutorial will move into constructing an oracle and finally testing that oracle.  This tutorial will also set remedy some common questions and misconceptions regarding oracles as well as other items.
