### ISSUE TITLE
[MagicSquareGame] Split task 1.1 in two parts

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/QuantumKatas#558]
Currently [task 1.1 of MagicSquareGame kata](https://github.com/microsoft/QuantumKatas/blob/main/MagicSquareGame/Tasks.qs#L40) consists of two parts - Alice's and Bob's moves validation, respectively. Both parts are covered with [one test](https://github.com/microsoft/QuantumKatas/blob/main/MagicSquareGame/Tests.qs#L25). However, this is not necessary, since the test validates Alice's and Bob's moves separately, without them depending on each other (unlike task 1.3 in which win condition depends on both moves). 

We can split the task in two independent parts (task 1.1.1 and 1.1.2) and cover them with separate tests, which would also offer the additional benefit of enabling CI validation for this task (see #539 for context).

**Comment by Manvi-Agrawal** [comment]
Hi @tcNickolas, I would like to take up this issue

**Comment by tcNickolas** [comment]
Sounds good!
