### ISSUE TITLE
MultiQubitGates Typo

### ISSUE THREAD

**Issue by vykrum** [microsoft/QuantumKatas#564]
Typo in the section [Other Types of Control Gates](https://hub.gke2.mybinder.org/user/microsoft-quantumkatas-wfqqa75j/notebooks/tutorials/MultiQubitGates/MultiQubitGates.ipynb) of the Multi Qubit Gates tutorial

<img width="1003" alt="Screenshot 2020-11-17 at 6 19 52 PM" src="https://user-images.githubusercontent.com/5621624/99392407-ab440580-2901-11eb-9daa-c2f8a3edc725.png">

Should be _control,_ not _target_

**Comment by vykrum** [comment]
Towards the end of the same section 
<img width="1019" alt="Screenshot 2020-11-17 at 9 42 13 PM" src="https://user-images.githubusercontent.com/5621624/99415614-fe2bb600-291d-11eb-90ee-b25592741167.png">

Should be _but_, not _by_

PS: Apologies for creating a new issue for these typos. Creating pull requests is beyond me.

**Comment by tcNickolas** [comment]
Thank you @vykrum for noticing these, and @nitish-awasthi for fixing them - excellent teamwork :-)
