### ISSUE TITLE
[CHSHGame] Dead-link in README.MD

### ISSUE THREAD

**Issue by MarrickLip** [microsoft/QuantumKatas#582]
"The [Lecture 20](https://cs.uwaterloo.ca/~watrous/CPSC519/LectureNotes/20.pdf) by John Watrous." link in [CHSHGame/README.md](https://github.com/microsoft/QuantumKatas/blob/main/CHSHGame/README.md) is dead.

https://cs.uwaterloo.ca/~watrous/CPSC519/LectureNotes/20.pdf is no longer available and I can't find a mirror -_-

**Comment by tcNickolas** [comment]
Looks like John Watrous did some reorganizing of his lecture notes, and it now resides at https://cs.uwaterloo.ca/~watrous/QC-notes/ (still as lecture 20). 

We'll need to go through the rest of the [links to his lecture notes](https://github.com/microsoft/QuantumKatas/search?q=watrous) and fix them as well.

Thank you for reporting!
