### ISSUE TITLE
Issue with task 1.4

### ISSUE THREAD

**Issue by 7rakir** [Microsoft/QuantumKatas#6]
Hello,
I'm confused by the solution of task 1.4 for which all tests seem to be passing: `Ry(2.0 * alpha, q);`

[This article](https://docs.microsoft.com/en-us/quantum/quantum-concepts-4-qubit?view=qsharp-preview#single-qubit-operations) states that Ry(a) = S.H.Rz(a).H.S^T where:
- S=S^T={{1,0},{0,i}}
- H=1/sqrt(2)×{{1,1},{1,-1}}
- Rz(a)={{e^(-i×a/2),0},{0,e^(i×a/2),0}}

The result of such multiplication is Ry(a) = {{cos(a/2),sin(a/2)},{sin(a/2),-cos(a/2)}} (after simplification using Euler's formula) as shown in [Wolfram|Alpha](http://www.wolframalpha.com/input/?i={{1,0},{0,i}}.((1%2Fsqrt(2))*{{1,1},{1,-1}}).{{e^(-i*z%2F2),0},{0,e^(i*z%2F2)}}.((1%2Fsqrt(2))*{{1,1},{1,-1}}).{{1,0},{0,i}}^T).

However, multiplication of the matrix with a qubit doesn't produce the required result.
The expected result is:
- |0〉 » cos(a)×|0〉 + sin(a)×|1〉
- |1〉 » -sin(a)×|0〉 + cos(a)×|1〉
... but the actual result of the multiplication is as follows:
- |0〉 » Ry(a×2).{1,0} = {cos(a),sin(a)} = cos(a)×|0〉 + sin(a)×|1〉
- |1〉 » Ry(a×2).{0,1} = {sin(a),-cos(a)} = sin(a)×|0〉 - cos(a)×|1〉

The expectation and actual result differ for input |1) in both signs, yet the tests pass. What am I missing?

**Comment by alan-geller** [comment]
@7rakir S^ (S-adjoint) isn't the same as S; it's {{1,0},{0,**-**i}}, not {{1,0},{0,i}}. I believe if you multiple through with the correct matrix for S^ you'll get the correct values.

**Comment by 7rakir** [comment]
Thank you very much. For some reason I misread that it's conjugate transpose (†) and not a simple transpose (T).
It's all clear now.
