### ISSUE TITLE
DumpOperation doesn't work inside %kata cells

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/QuantumKatas#629]
A Q# Jupyter Notebook cell like this:

    %kata T_TestName
    
    operation OperationName () : Double {
        // ...
        DumpOperation(2, ApplyToFirstTwoQubitsCA(CNOT, _));
        return 0.0;
    }

does not print a matrix of a CNOT operation, as expected. Instead, it either prints nothing (if I run it on a local IQ# installation) or prints DumpMachine output for a state which I suspect is the [Choi–Jamiołkowski state](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.preparation.preparechoistatea) for the given operation (if I run it on Binder).

DumpOperation works fine for me from regular cells (executed using %simulate), so I suspect something goes wrong when redirecting output streams with `%kata` magic vs the [DumpReferenceAndTarget operation](https://github.com/microsoft/QuantumLibraries/blob/5cb1f4323e8e81196fdd2a6e07867597c62a9ef2/Standard/src/Diagnostics/Emulation/Internal.cs#L51).

QDK version: 0.17.2105143879 (both for local setup and for Binder)

@anjbur I'd really appreciate it if you could look into this!

**Comment by Manvi-Agrawal** [comment]
Hi @tcNickolas @anjbur , adding this following line to the `KataMagic.cs` inside `Simulate()` seems to fix the bug.
```
qsim.OnDisplayableDiagnostic += channel.Display;
```

**Comment by tcNickolas** [comment]
That looks very promising! Could you send a pull request with the fix so
that we can validate it? Thank you!!

**Comment by Manvi-Agrawal** [comment]
I would love to do that. But I think it doesn't fix the problem completely

In **Superposition** kata, if I add `DumpOperation(2, ApplyToFirstTwoQubitsCA(CNOT, _));` , it works perfectly fine.
![Screenshot (79)](https://user-images.githubusercontent.com/40084144/121482252-95577880-c9ea-11eb-941f-d9f7639f1246.png)


However, in **BasicGates** kata, if I add `DumpOperation(2, ApplyToFirstTwoQubitsCA(CNOT, _));` , it works perfectly fine till it prints "Test passed" but then it prints the some extra output associated with `DumpOperation`

**SS1**
![Screenshot (82)](https://user-images.githubusercontent.com/40084144/121482975-4d852100-c9eb-11eb-9c4a-e20b092fdb2b.png)


**SS2** Extra output
![Screenshot (83)](https://user-images.githubusercontent.com/40084144/121483119-73122a80-c9eb-11eb-8285-fdd097345418.png)

**Comment by Manvi-Agrawal** [comment]
@tcNickolas , I am trying to figure out to figure out the cause of this odd behaviour b/w the **Superposition** and the **BasicGates** kata since they use a similar testing harness.

Initially I thought it might be due to the initial state preparation step in the **BasicGates** kata which converts **|0>** to **0.6*|0> + 0.8*|1>**, so I commented out the `statePrep` step but its not helping as evident from the above ss.

**Comment by tcNickolas** [comment]
One difference I see between Superposition and BasicGates is that Superposition only uses [plain version of the task operation](https://github.com/microsoft/QuantumKatas/blob/86c7a44e703187f7dafc4615e9cd5efa45f7d1e3/Superposition/Tests.qs#L39), and BasicGates uses both the [plain version](https://github.com/microsoft/QuantumKatas/blob/86c7a44e703187f7dafc4615e9cd5efa45f7d1e3/BasicGates/Tests.qs#L66) and the [controlled one](https://github.com/microsoft/QuantumKatas/blob/86c7a44e703187f7dafc4615e9cd5efa45f7d1e3/BasicGates/Tests.qs#L86). Might be something about the implementation of the controlled version of DumpOperation...

**Comment by Manvi-Agrawal** [comment]
Hi @tcNickolas ,  I also initially thought on the same lines. 

Finally found the culprit in `BasicGates`. It was the call to `AssertOperationsEqualsReferenced` function in the test. Removing this line now doesn't give the additional output. Unfortunately a large number of tests use this operation, so would need to think a fix for the same.

**Comment by tcNickolas** [comment]
Yeah, that operation is the core part of a lot of tests :-)
But [internally](https://github.com/microsoft/qsharp-runtime/blob/main/src/Simulation/TargetDefinitions/Decompositions/AssertOperationsEqualReferenced.qs#L56) it only calls the test operation again, so I would understand if we got two matrices in BasicGates, but not the DumpMachine output instead...

**Comment by Manvi-Agrawal** [comment]
Hi @tcNickolas, the controlled version of the operation is indeed troubling. Passing the basic version, gives two matrices.

**Comment by tcNickolas** [comment]
Aha, so it looks like there are two things in play here: 
1. Enabling printing DumpOperation output from the %kata magic, which your fix addresses.
2. `Controlled DumpOperation(new Qubit[0], (2, ApplyToFirstTwoQubitsCA(CNOT, _)));` prints DumpMachine output instead of matrix, but that happens regardless of the katas, I can reproduce this behavior in a regular Q# Jupyter Notebook cell.

I suggest we fix the first part in the Katas - that will definitely be an improvement, since a lot of the tests don't use controlled variants of the task operations. Meanwhile I'll try to track down the definition of the controlled variant of `DumpOperation` and file the second part as an issue against that repo.

**Comment by Manvi-Agrawal** [comment]
Hi @tcNickolas , I am observing same `DumpMachine` output in `RippleCarryAdder` kata, if I add `DumpOperation(2, ApplyToFirstTwoQubitsCA(CNOT, _));` in `LowestBitCarry` operation and then try to implement `TwoBitAdder` in Task 1.6. 

I am able to reproduce the behaviour of Adjoint DumpOperation in regular Q# Jupyter Notebook cell as you did for the Controlled Variant [here](https://github.com/microsoft/QuantumKatas/issues/629#issuecomment-858844667).
> Controlled DumpOperation(new Qubit[0], (2, ApplyToFirstTwoQubitsCA(CNOT, _))); prints DumpMachine output instead of matrix, but that happens regardless of the katas, I can reproduce this behavior in a regular Q# Jupyter Notebook cell.

Here is a screenshot for the same
![UnexpectedBehaviourOfAdjointDumpOperation](https://user-images.githubusercontent.com/40084144/121627354-d1dfae80-ca94-11eb-90bc-a1d4f8b23068.png)

**Comment by tcNickolas** [comment]
Yes, the reference solution for `TwoBitAdder` uses `Adjoint LowestBitCarry`, so it makes sense it fails in the same manner.

Good point about adjoint! I edited the issue to add it to the controlled.
