### ISSUE TITLE
Question about Task 2.11 (Superposition of two bit strings)

### ISSUE THREAD

**Issue by wsgac** [Microsoft/QuantumKatas#66]
Hi,

I've come up with a solution alternative to the one suggested in the reference, which - if it worked - would probably be conceptually simpler. The idea is that, given the qubit register and two boolean registers from the outside (in this case, from the test), I attach one additional qubit, in a way extending my quantum register by one. I then apply Hadamard gate to that qubit, essentially obtaining the following superposition:
```
1/sqrt(2) (|0>|0>...|0> + |1>|0>...|0>)
```
where I assume that the first qubit is my additional one. I then iterate through the first classical register and whenever its item is `true` I apply a `CNOT` between the `0th` and `ith` qubits, thus setting one half of the superposition. I then negate the first qubit with `X` and repeat the procedure for the second classical register. I finally discard my additional qubit and I'm left with my resultant qubit register.

Below is my take on implementing an operation according to the description above:
```qsharp
operation TwoBitstringSuperposition (qs : Qubit[], bits1 : Bool[], bits2 : Bool[]) : Unit {
        // ...
        using (q = Qubit()) {
            H(q);
            for (i in 0..Length(qs)-1) {
                if (bits2[i]) {
                    CNOT(q, qs[i]);
                }
            }
            X(q);
            for (i in 0..Length(qs)-1) {
                if (bits1[i]) {
                    CNOT(q, qs[i]);
                }
            }
            Reset(q);
        }
    }
```
The thing that puzzles me is that the test suite in QuantumKatas fails to pass. But I moved ahead and tried to simulate a simplified scenario, in which I specify the desired parameters of the superposition and then measure multiple repetitions. If I do it that way, the mechanism seems to work. Below is a test operator, which calls the one above in a `for` loop and gathers statistics:
```qsharp
operation TestTwoBitstringSuperposition (count: Int) : Int[] {
        mutable arr = new Int[4];
        using (q = Qubit[2]) {
            for (i in 1..count) {
                Set(Zero, q[0]);
                Set(Zero, q[1]);
                TwoBitstringSuperposition(q, [true,true], [false,false]);
                let res = [M(q[0]), M(q[1])];
                if (res[0] == Zero && res[1] == Zero) {
                    set arr[0] = arr[0] + 1;
                } elif (res[0] == Zero && res[1] == One) {
                    set arr[1] = arr[1] + 1;
                } elif (res[0] == One && res[1] == Zero) {
                    set arr[2] = arr[2] + 1;
                } elif (res[0] == One && res[1] == One) {
                    set arr[3] = arr[3] + 1;
                }
            }
            Set(Zero, q[0]);
            Set(Zero, q[1]);
        }
        return arr;
    }
```
It gives me sensible output, differing according to how I specify the boolean registers. I'm having trouble debugging the provided tests, so I'd like to ask you for help either making it work, or pointing out how my approach is wrong. Thanks!

**Comment by tcNickolas** [comment]
Your solution doesn't actually prepare the superposition of the two given bit strings, it prepares one of the bit strings at random with 50-50 chance.

Consider the simplest example possible: prepare superposition of |0⟩ and |1⟩ basis states (bits1 = [true], bits2 = [false]). After the two loops, right before Reset, the state of the qubits is |00⟩ + |11⟩ (with appropriate normalization). Reset measures the qubit q and applies X if necessary to convert it to |0⟩ state. If you measure one of the qubits in the superposition |00⟩ + |11⟩, the second one will be left either in |0⟩ state or in |1⟩ state, depending on the measurement result, but not in a superposition.

It is possible to make this approach work, but you'll need to convert the additional qubit to |0⟩ state by uncomputing it, not by measuring it - for example, you can find a position in which the bitstrings differ and do a CNOT with the corresponding qubit the as control and the additional qubit as the target - but then it stops being conceptually simpler :-)

**Comment by wsgac** [comment]
Thanks for the great explanation! So my means of zeroing the additional qubit (i.e. `Reset`) simply collapses the superposition I've built and by the time I was measuring my qubits proper, there was no more superposition to collapse, is that right?

I also want to clear one detail about your suggestion of 'uncomputing'. So, the configuration of superpositions between the additional qubit and the one corresponding to the first mismatch in bitstrings can be either 'straight' or 'diagonal' (meaning (q0 = |0⟩+|1⟩, qi = |0⟩+|1⟩) or (q0 = |0⟩+|1⟩, qi = |1⟩+|0⟩), respectively), and so the CNOT results in q0 becoming |0⟩ or |1⟩, respectively, after which measuring it no longer collapses our desired superposition. So the crux here is going with a unitary transformation (CNOT) instead of a measurement. Do I get this right?

**Comment by wsgac** [comment]
I've implemented your suggestion and it worked fine. Here's the code:
```qsharp
operation TwoBitstringSuperposition (qs : Qubit[], bits1 : Bool[], bits2 : Bool[]) : Unit {
        // Find first index where bit strings differ
        mutable mismatch = -1;
        for (i in 0..Length(qs)-1) {
            if (bits1[i] != bits2[i] && mismatch == -1) {
                set mismatch = i;
            }
        }
        // Allocate one additional qubit
        using (q = Qubit()) {
            H(q); // Produce superposition
            // Set one half of the superpositon...
            for (i in 0..Length(qs)-1) {
                if (bits2[i]) {
                    CNOT(q, qs[i]);
                }
            }
            // ...then another
            X(q);
            for (i in 0..Length(qs)-1) {
                if (bits1[i]) {
                    CNOT(q, qs[i]);
                }
            }
            // Uncompute the additional qubit
            CNOT(qs[mismatch], q);
            // Cleanup
            Reset(q);
        }        
    }
```
Thanks for a very enlightening discussion and keep up the great work :).
