### ISSUE TITLE
Do not prebuild projects that don't have .csproj file

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/QuantumKatas#662]
In prebuild script used by the Binder, we try to do `dotnet build` on all katas and tutorials listed in https://github.com/microsoft/QuantumKatas/blob/main/Dockerfile, regardless of whether they actually have a .csproj file to build:
https://github.com/microsoft/QuantumKatas/blob/a8437af4a1a06d24e6dd0bf915acaef0a4f0a045/scripts/prebuild-kata.sh#L7

We have several tutorials, ComplexArithmetic and LinearAlgebra, which are Python-based, and don't have an underlying .csproj file, so prebuilding them yields errors which look confusing in Binder log. It would be nice to check whether the folder has a .csproj file and run `dotnet build` only if it does, skipping that step otherwise. (The next line, `jupyter nbconvert`, should be executed regardless, since all prebuilt katas and tutorials have a Notebook frontend.)

**Comment by deepto98** [comment]
@tcNickolas  Hi, I'd like to work on this issue. If it isn't assigned already, can you please assign this to me?

**Comment by tcNickolas** [comment]
@deepto98 Sure! I recommend holding off the pull request for 24 hours to make sure it qualifies for Hacktoberfest :-)

**Comment by deepto98** [comment]
@tcNickolas I added this check in this PR (https://github.com/microsoft/QuantumKatas/pull/667). Do let me know if this would work. 
😃

**Comment by tcNickolas** [comment]
Yes, that looks like it works :-) Thank you!

**Comment by deepto98** [comment]
You're welcome. I want to contribute more to the project, do let me know if there are any other issues I can work on.
