### ISSUE TITLE
Measurement Task 1.7 - code passes even with more than one measurement

### ISSUE THREAD

**Issue by GaurangTandon** [Microsoft/QuantumKatas#68]
The comment description for that task reads:

    // You can use exactly one measurement.

The following code passes:

    operation TwoBitstringsMeasurement (qs : Qubit[], bits1 : Bool[], bits2 : Bool[]) : Int {
        let n = Length(qs);

        for(i in 0..n-1){
            if(M(qs[i]) == One){
                if(bits1[i] && bits2[i]){
                }elif(bits1[i]){
                    return 0;
                }else{
                    return 1;
                }
            }else{
                if(not bits1[i] && not bits2[i]){
                }elif(not bits1[i]){
                    return 0;
                }else{
                    return 1;
                }
            }
        }

        return -1;
    }

AFAICT, the above code makes n-1 measurements, if both the boolean bit arrays have different value only at the last bit.

**Comment by tcNickolas** [comment]
Good point, this is one of the older katas and the testing framework doesn't count the operations used, like the later (and more sophisticated) katas do. I'll need to revisit this at some point and see whether the rest of the tasks in the Measurements kata need to have more strict checks as well.

Thank you for pointing this out!

**Comment by tcNickolas** [comment]
This has been resolved as part of #101.
