### ISSUE TITLE
Update Quantum Katas project to be based on .NET6

### ISSUE THREAD

**Issue by ricardo-espinoza** [microsoft/QuantumKatas#683]
As part of planned work to change the base version of the QDK from .NET 3.1 to .NET 6, we'll need to update the Katas projects in conformance with this change. The main issue tracking this work can be found below:

https://github.com/microsoft/qsharp-compiler/issues/1224

**Comment by ricardo-espinoza** [comment]
A preview version of the Quantum Development Kit is now available in beta. You can try it out now in the following ways:

- Using the Quantum Katas in Binder, by going to: https://mybinder.org/v2/gh/Microsoft/QuantumKatas/feature/dotnet6?urlpath=/tree/index.ipynb
- Locally, by cloning the Katas repo and using branch `feature/dotnet6` instead of `main`, and then following the regular instructions available [here](https://github.com/microsoft/QuantumKatas#kata-locally).
- If you want to use the Visual Studio Code extension, you'll need to uninstall the regular version and try this one instead: [Microsoft Quantum Development Kit for Visual Studio Code .NET 6 Preview](https://marketplace.visualstudio.com/items?itemName=quantum.quantum-devkit-vscode-net6).

**Comment by tcNickolas** [comment]
The update to .NET6 is complete as of release 0.24.201332.
