### ISSUE TITLE
Task 1.4 in Basic Gates Kata is unclear

### ISSUE THREAD

**Issue by lwoodyiii** [microsoft/QuantumKatas#710]
Task 1.4 in the [Basic Gates Kata](https://github.com/microsoft/QuantumKatas/blob/main/BasicGates/BasicGates.ipynb) is unclear in the last Goal. It says:
_If the qubit is in superposition, change its state according to the effect on basis vectors._

- It is unclear which basis we are using; I think we should be explicit and say computational basis.

- "According to the effect" is unclear. According to the effect of what? In the solution workbook it becomes clear that it is referring to the Ry Gate's effect, but you don't know that is the gate in the beginning....

**Comment by tcNickolas** [comment]
This sentence doesn't make a lot of sense on its own, it's supposed to be read in the context of the previous two statements that describe the desired effect of the operation on the basis states. In this context, "basis vectors" are "basis vectors mentioned above", and "effect" is "the effect described above"
