### ISSUE TITLE
JointMeasurements - Task 7 - invalid code passes

### ISSUE THREAD

**Issue by GaurangTandon** [microsoft/QuantumKatas#74]
```
// Task 7**. Controlled X gate with arbitrary target
// Input: Two qubits (stored in an array of length 2) in an arbitrary
//        two-qubit state α|00⟩ + β|01⟩ + γ|10⟩ + δ|11⟩.
// Goal:  Change the two-qubit state to α|00⟩ + β|01⟩ + δ|10⟩ + γ|11⟩ using only single-qubit gates and joint measurements.
//        Do not use two-qubit gates.
operation ControlledX_General (qs : Qubit[]) : Unit {

    body (...) {
        CNOT(qs[0], qs[1]);
    }

    adjoint self;
}
```

The above code passes, even though it is written in the docstring that "Do not use two-qubit gates".

**Comment by tcNickolas** [comment]
This is similar to #68 - test harness is not sophisticated enough to validate this kind of restrictions. It is a little tricky to validate - it is very easy to check that the code doesn't use `CNOT` or `Controlled X` gates, but `CNOT` can be expressed using a wide variety of other gates (`CCNOT` or `Controlled Z` ), which means that we need indeed to prohibit any 2-qubit gates.

I'll need to think about it. Meanwhile, treat this as a helpful suggestion to direct the learning process - if a task asks to to implement `CNOT` in a certain way, you can of course just use the `CNOT` to pass the test, but you've hardly learned anything this way :-)

**Comment by tcNickolas** [comment]
#170 finally fixes this issue.
