### ISSUE TITLE
DeutschJozsaAlgorithm: Description of task 4.1

### ISSUE THREAD

**Issue by Acarreo** [Microsoft/QuantumKatas#75]
Where it says: Σᵢ (rᵢ xᵢ + (1 - rᵢ)(1 - rᵢ)) should be Σᵢ (rᵢ xᵢ + (1 - rᵢ)(1 - xᵢ))

**Comment by tcNickolas** [comment]
Nice catch, thank you! The fix is literally one character so I squeezed it in the https://github.com/Microsoft/QuantumKatas/pull/73.
