### ISSUE TITLE
Enable tests that are currently excluded with multicell solution tag

### ISSUE THREAD

**Issue by Manvi-Agrawal** [microsoft/QuantumKatas#806]
In [PR 539 : Updating notebooks validation script to exclude individual tasks](https://github.com/microsoft/QuantumKatas/pull/539), we excluded tasks in CHSHGame and MagicSquareGame because some tasks required implementing two code cells at once before running the test, so the first of the cells implemented is guaranteed to fail. 

Currently, the following notebooks have a `multicell_solution`
- CHSH Game and corresponding workbook
- Magic Square Game
- Oracles notebook

We can enable those tests in the workbook by using `raises-exception` cell tag which runs the cell but ignores any exceptions encountered during the cell execution. Here is a sample PR : https://github.com/microsoft/QuantumKatas/pull/805 which enables these tests in CHSH Workbook

However currently, we can only enable the Workbook tests and not the jupyter front-end notebook tests because `KataMagic` stores the results of its previous excutions whereas `CheckKataMagic` doesn't. For more details, here are the links [KataMagic code](https://github.com/microsoft/QuantumKatas/blob/main/utilities/Microsoft.Quantum.Katas/KataMagic.cs#L224-L235) and [CheckKataMagic code](https://github.com/microsoft/QuantumKatas/blob/main/utilities/Microsoft.Quantum.Katas/CheckKataMagic.cs#L217-L218)

@tcNickolas, @anjbur, maybe we can do this small change in `CheckKataMagic` to store the results of previous tests, so that we can enable those tests. Thoughts?

**Comment by tcNickolas** [comment]
We will be migrating the Katas to the new QDK that will use a different infrastructure (see https://devblogs.microsoft.com/qsharp/introducing-the-azure-quantum-development-kit-preview/ for the announcement), so we won't continue to improve the existing infrastructure of Q# notebooks magics. Closing this issue as "won't fix".

**Comment by Manvi-Agrawal** [comment]
Thanks @tcNickolas for your valuable guidance. 

Looking forward to the new kata experience. Just had a look at https://quantum.microsoft.com/en-us/experience/quantum-katas, and the experience looks way more polished :-)
