### ISSUE TITLE
[MultiQubitSystemMeasurements] Add code to Exercise 2 solution to show state in Pauli X basis

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/QuantumKatas#807]
Follow up to #804: it is possible to verify the math computation for the state in the Pauli X basis by preparing the given state and then applying an H gate to each qubit - the amplitudes of the computational basis states in the resulting state will match the amplitudes of the Pauli X basis states in the original state. I was tempted to write this code when reviewing the pull request, so it could be a good thing to add to the workbook solution.

**Comment by remilvus** [comment]
I can work on this task

**Comment by tcNickolas** [comment]
Sounds great! It should be rather straightforward, but let me know if you have any questions!
