### ISSUE TITLE
Systems of Equations not properly explained

### ISSUE THREAD

**Issue by hiibolt** [microsoft/QuantumKatas#893]
Hello!

On line 55 of the [Multi-Qubit Systems workbook](https://github.com/microsoft/QuantumKatas/blob/5c37733f27988c64deb92d41686893ccbf20fd6a/tutorials/MultiQubitSystems/Workbook_MultiQubitSystems.ipynb?short_path=8a49a5a#Exercise-1:-Show-that-the-state-is-separable), it is not properly explained how the constants are found. To my limited knowledge of math, is it not true that at least some of the constants needs to be known?

If so, how were they determined here?

**Comment by tcNickolas** [comment]
The solution to this system of equations is not unique, you can multiply the $\alpha$ and $\beta$ given as the solutions by any complex number with absolute value 1 and $\gamma$ and $\delta$ - by its adjoint and you'll get a valid solution as well. In practice, these solutions differ from the given one only by the global phases of the qubit states, which is not observable, so they are ignored. 

To solve the system, you can fix $\alpha$ to be a non-negative real number, and, taking into account the normalization requirement for both qubit states ($|\alpha|^2 + |\beta|^2 = 1$ and $|\gamma|^2 + |\delta|^2 = 1$), find out that  the absolute value of each of those numbers is $\frac1{\sqrt2}$; after this, you only need to adjust the relative phases of each number.
