### ISSUE TITLE
getting issue in exit command

### ISSUE THREAD

**Issue by ravi46kom** [microsoft/QuantumKatas#897]
Hi,
I'm getting a issue in container PowerShell, I'm running a the command '$result = docker exec -ti  container PowerShell "C:\download\abc.ps1' and in 'abc.ps1' there is a command 'exit 1'.
The case is that I'm getting all values in $result variable including $LASTEXITCODE But when I'm running "EXIT 1" the container PowerShell gets exited but not returning the exit value '1' in $result variable. I'm getting this unexpected behavior using container PowerShell only.

**Comment by tcNickolas** [comment]
This seems to be a PowerShell question not related to the use of the Quantum Katas.
