### ISSUE TITLE
Link in GroversAlgorithm to git database sample in readme file needs to include src to work

### ISSUE THREAD

**Issue by DOMARS** [Microsoft/QuantumKatas#99]
In this readme file for GroversAlgorithm: 
https://github.com/Microsoft/QuantumKatas/tree/master/GroversAlgorithm

The link to the Q# 
Q# Samples repository has an *implementation of Grover's search*.
https://github.com/Microsoft/Quantum/tree/master/Samples/DatabaseSearch
Returns a 404.

I believe it needs to include the src directory.
https://github.com/Microsoft/Quantum/tree/master/Samples/src/DatabaseSearch

Thank you for this great set of sample code.

**Comment by tcNickolas** [comment]
Nice catch, thank you! Do you want to open a PR to fix the link? If not, I'll get to it later.

**Comment by DOMARS** [comment]
@tcNickolas  - I will try my hand at a PR in this repo, as I would imagine there are many other things for you to work on.  :-)

**Comment by tcNickolas** [comment]
Resolved in https://github.com/Microsoft/QuantumKatas/pull/100 - thank you!
